jquery/jquery

test/unit/ajax.js
=> Ajax: Run the PATCH test only in IE8 on TestSwarm

src/css/curCSS.js, src/css/support.js
=> CSS: save 20 bytes in css/support

build/tasks/install_jsdom.js, build/tasks/node_smoke_tests.js, package.json
=> Build: use different versions of jsdom for Node and iojs testing

src/event.js, src/manipulation.js
Fixes gh-2301
+24 bytes, most of which come from event changes. The manipulation change adds just 5 bytes.
I've also tried to move `on` to a proper `/var/` directory but it only increased the size further.
Any ideas on how to reduce the size increase?
=> Remove internal args to on & remove methods

src/deferred.js, test/unit/deferred.js
=> Deferred: add .catch handler

src/ajax/parseJSON.js, src/attributes/support.js, src/attributes/val.js, src/css.js, src/css/support.js, src/manipulation/wrapMap.js, test/unit/support.js
Drop non-critical workarounds for Android 2.3.
Fixes gh-2483
Fixes gh-2505
=> Ajax:Attributes:CSS:Manipulation: Reduce Android 2.3 support

src/effects/Tween.js, test/unit/tween.js
This reverts commit b7a7dea95f84d6d8e5a8186d4fb09a762baf79bb.
Fixes #3064
=> Revert "Effects: Remove additional parameters of easings"

.gitignore, Gruntfile.js, package.json
* Bump eslint-config-jquery package to 0.1.4 version
* Add subtask "dist" to "eslint" task and add it to the build task list
* Make gitignore rule more flexible for the "dist" folder
Fixes gh-3169
=> Build: Improve ESLint configuration

.eslintrc, dist/.eslintrc, package.json, src/attributes/prop.js, src/attributes/val.js, src/core.js, src/core/access.js, src/css.js, src/data.js, src/effects.js, src/event.js, src/manipulation/getAll.js, src/serialize.js, src/traversing/findFilter.js, test/.eslintrc
=> Build: Update eslint config and fix associated errors

Gruntfile.js
Currently the "all" target for the eslint task includes way more than
the "dev" & "dist" targets combined and those 2 tasks are the one run in
`npm test`.
=> Build: Don't lint every file in dist/

src/deferred.js, test/unit/deferred.js
=> Deferred: Stop inventing jQuery.when() resolution values

test/node_smoke_tests/.eslintrc.json
cc @mgol
Fixes Node smoke tests
Ref gh-3385
=> Build: Use valid ecmaVersion

src/offset.js
=> Offset: Eliminate little-used internal function

.github/ISSUE_TEMPLATE.md
Fixed a typo in the github issue template - "acually" to "ac**t**ually"
=> Corrected typo in issue template

src/callbacks.js, test/unit/callbacks.js
=> Callbacks: Prevent add() from unlocking with-memory lists

src/core/stripAndCollapse.js, src/var/rnothtmlwhite.js
Update links to HTML spec for [src/core/var/stripAndCollapse.js](https://github.com/jquery/jquery/blob/master/src/core/stripAndCollapse.js)
=> Docs: Update links to HTML spec for stripAndCollapse

test/data/iframeTest.js, test/data/testinit.js, test/unit/offset.js
Hopefully this fixes iOS testing: http://swarm.jquery.org/job/5226
=> Tests: Improve offset test setup and labels

test/data/offset/boxes.html
=> Tests: Be even more async for iOS

test/data/testinit.js, test/data/testrunner.js
=> Tests: Attach test iframes to the body for visibility-dependent code

test/data/testinit.js, test/unit/offset.js
=> Tests: Allow a mock QUnit.test for perfect testIframe fidelity

test/unit/offset.js
=> Tests: Reset iframe window scroll after updating html/document position

src/offset.js
Always let @gibson042 review it one more time ^_^
=> Offset: fix error from bad merge in #3695

.travis.yml
Node.js 4 & 9 are ending their life, Node.js 10 has just been released.
=> Build: Test on Node 10, stop testing on Node 4 & 9

src/css.js, src/css/support.js, test/data/css/cssWidthBrowserZoom.html, test/unit/css.js
=> CSS: Correctly detect scrollbox support with non-default zoom

README.md
Adds a license scanning badge to quickly show dependency license compatibility based on FOSSA scans.
=> README: Add FOSSA license scan status badge

README.md
Something we meant to do a long time ago.
=> Docs: add gitter badge to README.md

test/unit/css.js
Ref gh-4007
Ref gh-4028
Tests for gh-4028. Issue gh-4007.
=> Tests: Add tests for not auto-appending "px" to CSS Grid properties

Gruntfile.js, package.json, test/.eslintrc.json, test/data/testinit-jsdom.js, test/unit/basic.js
The basic test suite is now run in jsdom.
=> Build: Run the basic test suite in jsdom

.travis.yml
Test on Node.js 12, stop testing on Node.js 6 & 11.
Node.js 12 has been released, versions 6 & 11 are EOL.
=> Build: Test on Node.js 12, stop testing on Node.js 6 & 11

Gruntfile.js, external/npo/npo.js
Ref gh-4445
This updates npo.js to the latest version and includes the unminified source instead just to make it more readable.
=> Tests: update npo.js and include unminified source instead

test/unit/selector.js
Ref https://github.com/jquery/sizzle/pull/450
=> Tests: Port changes from Sizzle

src/selector.js, src/selector/rbuggyQSA.js, test/unit/selector.js
With new selector code doing less convoluted support tests, it was possible
to extract a lot of logic out of setDocument & also reduce size.
=> Selector: reduce size, simplify setDocument

test/unit/offset.js
This PR backports a looser assertion from `master` where the browsers passes
offset tests. This should fix the TestSwarm failures that we have in Chrome for Android, see: http://swarm.jquery.org/result/3341025
=> Tests: Fix offset fractions tests in Chrome for Android

build/release/dist.js
Without this change passing `--dry-run` to jquery-release still pushes to the
jquery-dist repository which is dangerous as one can assume `--dry-run` to be
safe from external side effects.
=> Build: Support jquery-release --dry-run flag

src/manipulation.js, src/selector.js
Use the `nodeName` util where possible to save size.
-20 bytes
=> Manipulation:Selector: Use the nodeName util where possible to save size

.travis.yml
Run tests on Node.js 13 in addition to 8, 10 & 12.
=> Build: Run tests on Node.js 13 in addition to 8, 10 & 12

.travis.yml
Run tests on Firefox ESR as well.
=> Build: Run tests on Firefox ESR as well

test/unit/manipulation.js
With Microsoft going Chromium with Edge, its old EdgeHTML issues were all
removed. :(
=> Docs: Update links to EdgeHTML issues to go through Web Archive

.eslintignore, dist/.eslintrc.json
While we have absolutely no style-related expectations to our minified file,
we do care that it's valid ES 5.1. This is now verified.
Fixes gh-3075
=> Build: Lint the minified jQuery file as well

.mailmap, AUTHORS.txt
Add Christian Oliff to `.mailmap` & `AUTHORS.txt`.
=> Build: Add Christian Oliff to .mailmap & AUTHORS.txt

.travis.yml, package.json
Test the no-Sizzle build on Travis. This will make it possible to modify instructions at https://github.com/jquery/jquery/wiki/Release-process to only look at Travis instead of running the tests manually.
=> Build: Test the no-Sizzle build on Travis

.travis.yml
Test on Node.js 14, stop testing on Node.js 8 & 13.
=> Build: Test on Node.js 14, stop testing on Node.js 8 & 13

build/fixtures/README.md
Update the link to the jsdom repository
=> Docs: Update the link to the jsdom repository

test/unit/manipulation.js
Add tests for recently fixed manipulation XSS issues.
Ref gh-4642
Ref gh-4647
=> Tests: Add tests for recently fixed manipulation XSS issues

build/fixtures/README.md, test/unit/manipulation.js
Hello,
This PR will fix : 
- 1 typo in `build/fixtures/README.md`
- 2 typos in `test/unit/manipulation.js`
Cheers! :robot:
=> Docs: Fix typos

src/.eslintrc.json, src/ajax.js, src/ajax/xhr.js, src/attributes/classes.js, src/core.js, src/core/access.js, src/core/nodeName.js, src/css.js, src/deprecated/event.js, src/dimensions.js, src/effects.js, src/effects/Tween.js, src/event.js, src/event/trigger.js, src/selector.js, src/serialize.js
- Correct code indentations based on Core Style Guide
(https://contribute.jquery.org/style-guide/js/#spacing)
- Add rules to `src/.eslintrc.json` to enable "enforcing consistent indentation",
with minimal changes to the current code.
=> Build: Correct code indentations based on jQuery Style Guide

CODE_OF_CONDUCT.md, Gruntfile.js, LICENSE.txt, package.json, src/wrapper.js
Docs: Update the copyright notice to mention the OpenJS Foundation
So far they were all about the JS Foundation.
=> Docs: Change JS Foundation mentions to OpenJS Foundation

build/release/dist.js, package.json, src/core/nodeName.js, src/css/isAutoPx.js, src/css/var/getStyles.js, src/css/var/isHiddenWithinTree.js, src/css/var/swap.js, src/data/var/acceptData.js, src/traversing/var/dir.js, src/traversing/var/siblings.js, src/var/isWindow.js
Update eslint-config-jquery, fix linting violations.
Ref jquery/eslint-config-jquery#15
Ref jquery/eslint-config-jquery#16
=> Build: Update eslint-config-jquery, fix linting violations

build/release.js
Release: Remove an unused chalk dependency
Chalk was used for a Sizzle version check that's no longer there on `master`.
=> Release: Remove an unused chalk dependency

test/middleware-mockserver.js
Removed an unused value in test code.
=> Tests: Remove an unused local variable

src/ajax/script.js
Don't use a script tag for JSONP requests unless for cross-domain requests
or if scriptAttrs are provided. This makes the `responseJSON` property available
in JSONP error callbacks.
This fixes a regression from jQuery 3.5.0 introduced in gh-4379 which made
erroneous script responses to not be executed to follow native behavior.
The 3.x-stable branch doesn't need this fix as it doesn't use script tags for
regular async requests.
Ref gh-4771
Ref gh-4773
Ref gh-4379
+6 bytes
* ~~New tests have been added to show the fix or feature works~~ This fixes an existing test from #4773
=> Ajax: Make responseJSON work for erroneous same-domain JSONP requests

CONTRIBUTING.md, README.md, build/release/dist.js, package.json, test/unit/offset.js
The default branch was updated, this updates the remaining occurrences in code
& comments.
=> Build: Rename master to main across the repository

.travis.yml
Node.js 10 is kept for now despite being EOL'd as that's what our current
infrastructure relies on.
=> Build: Test on Node.js 16 instead of 15

README.md
update readme:
- irc.freenode.net works broken, and update irc address to libera based on the infomation from  https://github.com/jquery/irc.jquery.org/issues/24
- fix LAMP dead link
=> update irc to libera and fix LAMP dead link

.github/workflows/node.js.yml
Separate the install step from running tests in GitHub Actions.
Also, update the "Run test" label to "Run tests".
=> Build: Separate the install step from running tests in GitHub Actions

CONTRIBUTING.md
=> Docs: add link to preview the new CLAs

.github/dependabot.yml
Automated PRs to update GitHub Action versions.
I noticed some of the GitHub Action workflows were using older versions. It'd be good to use Dependabot to help keep them up-to-date.
=> Build: Add dependabot.yml config (GitHub Actions)

.github/workflows/codeql-analysis.yml, .github/workflows/node.js.yml
This is an aggregated PR of dependabot GitHub Actions updates to avoid 4 separate PRs.
Summary of individual changes:
_1/4. Build(deps): Bump github/codeql-action from 1 to 2_
Bumps [github/codeql-action](https://github.com/github/codeql-action) from 1 to 2.
- [Release notes](https://github.com/github/codeql-action/releases)
- [Changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
- [Commits](https://github.com/github/codeql-action/compare/v1...v2)
---
updated-dependencies:
- dependency-name: github/codeql-action
dependency-type: direct:production
update-type: version-update:semver-major
...
_2/4. Build(deps): Bump actions/cache from 2 to 3_
Bumps [actions/cache](https://github.com/actions/cache) from 2 to 3.
- [Release …
=> Build: Update GitHub Actions

build/fixtures/README.md
The previous details were showing their age, e.g. mentions about browsers
not supporting ES2015. The story with ES modules is more complex as it's also
about loaders but to keep the README simple, let's just make it more up to date
with typical usage.
=> Docs: Update the README of the published package

package.json
This will resolve the following security issues:
* Path Traversal in Grunt: https://github.com/advisories/GHSA-j383-35pm-c5h4
* Race Condition in Grunt: https://github.com/advisories/GHSA-rm36-94g8-835r
=> Build: Update Grunt from 1.4.1 to 1.5.3

.github/workflows/node.js.yml
Test on Node.js 18 & 19, stop testing on Node 12
=> Build: Test on Node.js 18 & 19, stop testing on Node 12

src/selector.js
=> Selector: Rename rcombinators to rleadingCombinator

build/release/cdn.js
=> Release: add support for md5 sums in windows

.github/workflows/node.js.yml
=> Build: Test on Node.js 20, stop testing on Node.js 14 & 19

src/manipulation/domManip.js, test/unit/ajax.js, test/unit/css.js, test/unit/traversing.js
Fixes typos found by [codespell](https://github.com/codespell-project/codespell).
=> Docs: Fix typos found by codespell

.mailmap
Update my preferred email in the mailmap so future commits use the right email.
=> Build: switch preferred email for timmywil

.mailmap
Ref https://github.com/jquery/jquery/pull/5306
=> Build: Update my mailmap entry

CONTRIBUTING.md
=> Docs: update watch task in CONTRIBUTING.md

.github/workflows/node.js.yml, build/tasks/build.js, package.json
- one fileOverrides per build
- only run the lint build when running lint
=> Build: fix inconsistent builds in Node 20

AUTHORS.txt, Gruntfile.js, build/release/authors.js, package-lock.json, package.json
- the new script pulls all authors from the Sizzle repo
- added temporary grunt task for releases
3.x version of #5395
=> Build: migrate grunt authors to a custom script

src/data/Data.js, src/effects.js, src/manipulation.js, src/manipulation/domManip.js, src/queue.js
* Return the new value from `set(owner, key, value)`.
* Use `set(owner, key, value)` rather than `access(owner, key, value)`.
Improvements noticed in passing.
```
main @88690ebfc8b5ef8b1e444326c664b590ecc0b888
raw     gz Filename
-44    -17 dist/jquery.min.js
-35    -16 dist/jquery.slim.min.js
-44    -21 dist-module/jquery.module.min.js
-35    -15 dist-module/jquery.slim.module.min.js
```
=> Data: Refactor to reduce size

build/release.js
Update the release build command to `npm run build:all` on the 3.x-stable branch.
=> Release: update build command in Release.generateArtifacts

build/release/dist.js
- this became necessary due to the addition of the prepare script
- scripts aren't needed and don't work in the dist repo
3.x version of #5404
=> Release: remove scripts and dev deps from dist package.json

build/release.js
Only push the versioned files to the CDN repo.
=> Release: only publish versioned files to cdn

build/release/dist.js
- Add the dist-module folder and its files to the dist repo
- Add the 2 package.json's and node wrappers to extras
=> Release: copy dist-module folder as well

build/release.js
Fixes gh-5411 
The factory files were not distributed as they needed to be added to the `distFiles` list.
=> Release: add factory files to release distribution

package.json
- this will soon be replaced by a new GH actions workflow
=> Build: update jenkins script to only build

test/unit/css.js
Use allowlist instead of whitelist.
=> Tests: Use allowlist instead of whitelist

package-lock.json, package.json, test/runner/reporter.js
Add diffing to test reporter.
This idea came from QUnit, but I added special diffing for when the values are numbers.
=> Tests: add diffing to test reporter

test/runner/reporter.js
- Show actual and expected values even if they are falsey.
- Also leave out message if none was provided, rather than printing `undefined`.
=> Tests: show any and all actual/expected values

.github/workflows/browserstack.yml
- fixes cancelled workflows when multiple PRs are merged in quick succession to both the main and 3.x-stable branches
=> Tests: include github ref in concurrency group

src/event.js, test/unit/event.js
In Firefox, alert displayed just before blurring an element dispatches
the native blur event twice which tripped the jQuery logic if a jQuery blur
handler was not attached before the trigger call.
This was because the `leverageNative` logic part for triggering first checked if
setup was done before (which, for example, is done if a jQuery handler was
registered before for this element+event pair) and - if it was not - added
a dummy handler that just returned `true`. The `leverageNative` logic made that
`true` then saved into private data, replacing the previous `saved` array. Since
`true` passed the truthy check, the second native inner handler treated `true`
as an array, crashing on the `slice` call.
The same issue could happen if a handler returning `true` is attached before
triggering. …
=> Event: Increase robustness of an inner native event in leverageNative

eslint.config.js, test/bundler_smoke_tests/run-jsdom-tests.js, test/data/csp-nonce-external.js, test/data/csp-nonce-globaleval.js, test/data/csp-nonce.js, test/jquery.js, test/unit/attributes.js, test/unit/css.js, test/unit/data.js, test/unit/deferred.js, test/unit/effects.js, test/unit/event.js, test/unit/manipulation.js, test/unit/offset.js, test/unit/traversing.js
- Audited the eslint flat config and filled in some gaps
- Added ecma versions where appropriate
=> Build: improve specificity of eslint config; add ecma versions

.release-it.cjs, build/release/post-release.sh, build/release/pre-release.sh, package.json
- also fix tagging the release in the dist repo
I was attempting the release and ran into some minor issues. I did some more manual dry runs of the pre-release.sh and post-release.sh scripts and this *should* work now.
=> Release: fix running pre/post release scripts in windows

.release-it.cjs, build/release/README.md, package.json
See https://github.com/release-it/release-it/issues/1128#issuecomment-2224692805
=> Release: set preReleaseBase in config file

build/release/dist.js, eslint.config.js
See https://github.com/jquery/jquery/pull/5522#discussion_r1695742620
=> Build: align eslint config with 3.x branch as much as possible

test/data/mock.php
See https://github.com/jquery/jquery/pull/5531#discussion_r1728140419
=> Tests: align mock.php spacing with 3.x-stable branch

README.md
- Add a section about which versions and branches are under active development
- Provide links to download the latest version, get commercial support from HeroDevs, or learn more about our version support
- Switch header format to be more consistent with our other markdown files
- Lint JS code
=> Docs: add version support section to README

.github/workflows/codeql-analysis.yml
This is backported from Core at:
https://github.com/jquery/jquery/blob/19716254877870ecd649272cadd00a0d0ff8be01/.github/workflows/codeql-analysis.yml
We're going to release the next 3.x version soon; I thought we should check for obvious issues before that - not only on the `main` branch.
=> Build: Add a CodeQL non-mandatory check

.github/workflows/browserstack-dispatch.yml, .github/workflows/browserstack.yml, .github/workflows/codeql-analysis.yml, .github/workflows/filestash.yml, .github/workflows/node.js.yml, .github/workflows/verify-release.yml
Align actions versions with what the `main` branch uses. Look at `git blame` for the `main` branch to see more details about specific versions.
=> Build: Bump GitHub Actions

.github/workflows/browserstack.yml
=> Build: Test on iOS 18

test/data/mock.php, test/unit/ajax.js
Also, fix `mock.php` formatting to not fail the
`jQuery.get( String, null, String )` test in PHP mode.
Ref gh-4989
Ref jquery/api.jquery.com#1208
=> Tests: Add tests for `jQuery.get( String, null-ish, null-ish, String )`

README.md
=> Docs: update herodevs link in README
