jquery/jquery

.travis.yml

Run Travis tests on a container infrastructure to make it start faster.
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/

Build: Speed up the Travis build

---

test/unit/data.js

This should fix "Java out of date" errors on BrowserStack.
Fixes gh-1938

Data: Use a PDF object instead of a Java applet for acceptData testing

---

src/css/curCSS.js
src/css/support.js
test/unit/support.js

This hack turns out to be needed by Android 4.0-4.3
Refs gh-1815
Refs gh-1820

Css: Restore the hack to get pixels for .css('width') etc.

---

test/unit/data.js

BrowserStack regularly has outdated Java in their IE instances causing our
data tests to hang & give no output. Skip the tests that create applets,
applets are treated in the same way as an embed elements which we're already
testing.
Fixes gh-1938
(note to myself: if accepted, remember to cherry-pick this to `2.1-stable` & `1.11-stable` together with #2028)
Original description:
BrowserStack regularly has outdated Java in their IE instances causing our
data tests to hang & give no output. Skip the assertion if the test is run
via TestSwarm.

Data: Drop the tests relying on applets

---

package.json
src/core/support.js
src/css/support.js

The latest version supporting Node.js is 3.1.2; some workarounds are not needed
for this version. For example, in jsdom 3.1.2 a document created via
document.implementation.createHTMLDocument( "" ) has a body.
Fixes gh-2153

Core: Update tested jsdom, drop obsolete workarounds

---

src/core.js
test/unit/core.js

I was able to reproduce on an iPhone 5s and iPhone 6 plus in iOS 8.2. Additionally, I tested AMD and minified versions for posterity. Let me know if I missed something.
Perf difference seems to be [negligible](http://jsperf.com/jquery-each-vs-no-jit-error).
Fixes gh-2145

Core: add workaround for iOS JIT error in isArrayLike

---

.gitignore
.jscsrc
.jshintignore
Gruntfile.js
build/tasks/node_smoke_tests.js
package.json
src/core.js
test/.jshintrc
test/node_smoke_tests/.jshintrc
test/node_smoke_tests/document_missing.js
test/node_smoke_tests/document_passed.js
test/node_smoke_tests/document_present_originally.js
test/node_smoke_tests/iterable_with_native_symbol.js
test/node_smoke_tests/iterable_with_symbol_polyfill.js
test/node_smoke_tests/lib/ensure_global_not_created.js
test/node_smoke_tests/lib/ensure_iterability_es6.js
test/node_smoke_tests/lib/ensure_jquery.js
test/unit/core.js

Make iterating over jQuery objects possible using ES 2015 for-of:
for ( node of $( "<div id=narwhal>" ) ) {
console.log( node.id ); // "narwhal"
}
Fixes gh-1693
TODO:
@rwaldron, could you have a look if it's safe to include this in 3.0.0?

Core: Make jQuery objects iterable

---

src/.jshintrc
src/ajax.js
src/core/ready.js
src/deferred.js
src/effects.js
src/queue/delay.js
src/var/clearInterval.js
src/var/clearTimeout.js
src/var/setInterval.js
src/var/setTimeout.js

Fixes gh-2177
+28 bytes.
An alternative to #2391 (+60), #2392 (+51) & #2394 (+40).

Core: Use window.setTimeout & friends instead of global equivalents

---

src/core/access.js

jQuery.access was never documented, there is no need to keep it exposed.
Fixes gh-2513

Core: Don't expose jQuery.access

---

src/core.js
test/unit/core.js

- This is a little more bulletproof in regards to future JS type additions.
- It is only different than what we currently have in one case.
- While the documentation has good examples, we need to be more explicit about how our isNumeric tries to coerce strings.
Fixes gh-2662

Core: make isNumeric limited to strings and numbers

---

src/attributes/attr.js
test/unit/attributes.js

- This is just legacy behavior that somehow stuck around. No docs changes needed.
Fixes gh-1759

Attributes: do not set properties to false when removing booleans

---

src/core/ready.js
test/data/event/interactiveReady.html
test/unit/event.js

- Now that dom ready is always synchronous, we don't have to deal with ensuring sync execution order.
- I actually couldn't reproduce the IE9 issue where DOM below scripts is not actually interactive, but I ran into a different issue with IE10 (I think it was mostly a test issue, but it had to do with document.write behaving differently so I didn't mess with it). Either way, I just kept the proposed solution of checking doScroll, effectively excluding IE9-10.
Fixes gh-2100

Core: use interactive to evaluate dom ready

---

test/unit/event.js

From my preliminary tests, the `DOMNodeInserted` event is still supported in our supported browsers.
Fixes gh-2055

Event: Ensure delegation doesn't error on comment nodes

---

test/data/event/focusElem.html
test/unit/event.js

Relatively easy fixes, although I did have a question about one strange VML-related test.

Event: Make event aliases optional in unit tests

---

src/deferred.js
test/unit/deferred.js

- This probably needs revision, but in the process of fixing #2546, I took a stab at #2018, but I'm not as familiar with this code as @jaubourg or @gibson042.
- -6 bytes
Fixes gh-2546
Fixes gh-2018

Deferred: synchronize single and multiple target handling in $.when

---

src/ajax/parseXML.js
src/ajax/xhr.js
src/core/support.js
src/css/curCSS.js
src/css/showHide.js
src/css/support.js
src/css/var/getStyles.js
src/data/Data.js
src/deferred/exceptionHook.js
src/effects/Tween.js
src/event.js
src/event/focusin.js
src/manipulation/getAll.js
src/manipulation/support.js
src/offset.js
test/unit/ajax.js
test/unit/basic.js
test/unit/css.js
test/unit/dimensions.js
test/unit/effects.js
test/unit/event.js
test/unit/manipulation.js
test/unit/offset.js

Support comments that were lacking the final IE/Edge version that exhibits
the bug were checked & updated. Links to the Chromium bug tracker were updated.
Code in tests related to unsupported browsers (like Android 2.3 in non-basic
tests) has been removed.
Fixes gh-2868
The first commit is PR #2948, I just didn't want to introduce conflicts between my 2 PRs. I'll rebase once that lands.

Docs:Tests: Remove obsolete code from tests, update support comments

---

build/tasks/build.js
src/exports/global.js

1. Strip excessive "use strict" pragmas when building (1st commit)
2. Strip the strict-mode related comment in exports/global.js (2nd commit)
Only the first commit is relevant to #3077, the second one was added mostly because it may reduce confusion and is also related to strict mode. If it's controversial, I may land only the first one.

Build: Strip excessive "use strict" pragmas when building

---

src/event.js
src/event/trigger.js
test/unit/event.js

In Firefox, called `stop(Immediate)Propagation` methods,
in capturing phase prevents receiving focus
See https://codepen.io/markelog/pen/pyBXOr.
/cc @bzbarsky
Probably not spec violation, but still pretty weird...
Fixes gh-3111

Events: don't execute native stop(Immediate)Propagation from simulation

---

src/attributes/attr.js
test/unit/attributes.js

Attribute hooks are determined for the lowercase versions of attribute names
but this has not been reflected in the bool attribute hooks. The code that
temporarily removed a handler to avoid an infinite loop was removing an
incorrect handler causing stack overflow.
Fixes gh-3133
Refs gh-2914
Refs gh-2916
+2 bytes

Attributes: Avoid infinite recursion on non-lowercase attribute getters

---

src/deferred.js
test/unit/deferred.js

Progress parameters are now correctly propagated from a deferred to which
another deferred resolved unwrapping it.
Thanks to @gibson042 for the report and a clear description of the problem
and the needed fix.
Fixes gh-3062
I'd like to get it in 3.0.0 as this bug is really unexpected and we've had a related external report.
Please review @jquery/core.

Deferred: Propagate progress correctly from unwrapped promises

---

src/core/ready.js
src/core/readyException.js
test/unit/core.js

Re-throw errors that happened in callbacks wrapped in jQuery ready
Also, expose jQuery.readyException that allows to overwrite the default
ready error handler.
Fixes gh-3174

Core: Re-throw errors that happened in callbacks wrapped in jQuery ready

---

Gruntfile.js
package.json

The PR makes it possible to use the new ESLint 3.x that's incompatible with Node.js older than 4.x but at the same time allows to build jQuery in an older Node. The tasks using problematic modules (like ESLint & jsdom) are skipped there.
Fixes gh-3222
cc @markelog

Build: Skip running ESLint on Node.js 0.x

---

build/tasks/build.js
src/exports/global.js
src/jquery.js
test/data/testinit.js
test/unit/core.js

- For compability reasons, we had already added the global
in AMD mode, but without noConflict. This adds back noConflict
to AMD (which fixes noConflict mode in the tests).
Fixes gh-2930

Core: expose noConflict in AMD mode

---

src/offset.js
test/unit/offset.js

I assume this previously worked (except IE<=11+ which crashed) before 0e4477c676db0427bb9b0bf39df8631501e62f24.
Also previously when `if ( rect.width || rect.height )` failed it would return `rect` which would be the `getBoundingClientRect()` object containing top/bottom/left/right along with the width/height of 0. The top/left in there would probably be quite misleading?
Fixes [gh-3267](https://github.com/jquery/jquery/issues/3167)

Offset: report offset for 0 sized elements

---

.eslintignore
.eslintrc-browser.json
.eslintrc-node.json
.eslintrc.json
.npmignore
Gruntfile.js
dist/.eslintrc.json
src/.eslintrc.json
test/.eslintrc.json
test/node_smoke_tests/.eslintrc.json
test/promises_aplus_adapters/.eslintrc.json

1. Use the short name of the preset in the config.
2. Run ESLint first on non-minified files.
3. Explicitly specify environments in every config file (those settings cascade
which means we've been assuming a Node.js environment where we shouldn't have).
I found these when working on https://github.com/jquery/jquery-migrate/pull/238.
cc @markelog

Build: ESLint setup improvements

---

.travis.yml
Gruntfile.js

Node.js 0.12 is no longer supported by upstream. So far we had to keep
a workaround that would skip running ESLint there (or even load its task)
as it no longer supports Node.js <4; the same applied to Node smoke tests
as jsdom has also dropped support for those old Node versions. Those
workarounds have been removed now.
Ref 030191ae32dfcb7ecb2efb61d17a4964a3633e44

Build: Drop support for building on Node.js 0.12

---

package.json

@mgol recently reported in jzaefferer/commitplease#91 that commitplease failed with valid commit messages. That happened because the regular expressions configured here in package.json triggered for any word with a prefix "ref", like reformat or refactor. This PR fixes those regular expressions.
~~~* [ ] New tests have been added to show the fix or feature works~~~
~~~* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~~
Commit messages used to fail the style check if they contained a word
starting with "ref", like reformat or reference, in their message body.
Refs jzaefferer/commitplease#91

Build: fix markerPattern and ticketPattern regexes in package.json

---

test/jquery.js

Tests: Update the loader so test pages always get jQuery

---

src/manipulation.js
test/unit/manipulation.js

Fixes gh-3439
```
raw     gz Sizes                                                            
267269  79153 dist/jquery.js                                                   
86863  30052 dist/jquery.min.js                                               
raw     gz Compared to master @ bf3a43eff8682b59cec785be6003753fa4b93706    
+59    +19 dist/jquery.js                                                   
-1     +9 dist/jquery.min.js
```

Manipulation: Restrict the tbody search to child nodes

---

src/effects.js
test/unit/effects.js

9d822bc1c13dd3393b418210a99537c22c06f2c3 failed an effects test (cf. https://github.com/jquery/jquery/pull/3470#issuecomment-271388489 ), but it turns out that things were already broken in subtle ways when animations spawn each other:
* immediately-done animations miss the final progress notification
* callbacks are registered _after_ the first tick
* animations get skipped when old ones are forcefully stopped mid-tick
Each fix revealed the next flaw, so all are addressed here in order to resolve the current CI failure. I should probably make real issues so they can be resolved by this PR.

9d822bc1c13dd3393b418210a99537c22c06f2c3 followup

---

src/traversing.js
test/index.html
test/unit/traversing.js

Add support to `$.fn.contents()` for [HTMLTemplateElement](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template).
Related with #3436

Traversing: $.fn.contents() supports HTMLTemplateElement

---

src/css.js
src/css/curCSS.js
test/unit/css.js

Fixes gh-3144
Closes gh-3199
This PR adds suppport for CSS Custom Properties (a.k.a. CSS Variables). This is a finalized version of the PR #3199 with passing tests.

CSS: Support custom properties

---

test/node_smoke_tests/lib/ensure_iterability_es6.js

Fix incorrect assert name for ensure_iterability_es6. Follows-up bb026fc1.

Tests: Fix incorrect assert name for ensure_iterability_es6

---

src/offset.js
test/data/offset/boxes.html
test/unit/offset.js

Makes `.offset()` always relative to the document and `.position()` always relative to the closest [containing block](https://drafts.csswg.org/css-display-3/#containing-block) offsetParent (if any).
Some new tests fail on IE\<11 (where `document.documentElement.getBoundingClientRect()` erroneously includes margins and disregards viewport scrolling), and have been manually disabled/patched up.
Fixes gh-3080
Fixes gh-3107
Closes gh-3096
Ref gh-3479

Fix .offset() and .position() bugs

---

src/core.js
test/unit/core.js
test/unit/deferred.js

Generators and async functions are still functions (cf. [ECMAScript Language Specification](http://www.ecma-international.org/ecma-262/7.0/#sec-generatorfunction-objects)), and we can recognize them with `typeof` (but still need a guard to reject elements).
Fixes gh-3600
Fixes gh-3596

Core: Update isFunction to handle unusual-@@toStringTag input

---

src/css.js

Firefox 35 and newer support `style.float` directly so we don't have to map `float` to `cssFloat` any more.
Maybe we could deprecate `jQuery.cssProps`? It's not documented and we now removed its last reason to exist from the Core point of view.

CSS: Drop the float mapping from cssProps

---

src/ajax.js
src/core.js
src/effects.js
src/manipulation.js
test/unit/ajax.js
test/unit/css.js
test/unit/dimensions.js
test/unit/support.js

This PR updates IE/Edge-related support comments (to e.g. update their status for Edge 15) and tweaks some tests that had to be relaxed in the past - most notably smaller precision in some dimensions tests.
*  ~~New tests have been added to show the fix or feature works~~

Docs:Tests: Update IE/Edge-related support comments & tests

---

src/css.js
test/unit/dimensions.js

Fixes gh-3589
Per [spec](https://drafts.csswg.org/css-box/#cb), a scrollbar gutter is excluded from content dimensions. But we want to include it in `.innerWidth`/`.innerHeight`/`.outerWidth`/`.outerHeight`, and therefore must calculate it from other data.
I also renamed functions and variables for clarity (but kept that work in its own commit for easier reviewing).
It's surprisingly big:
```
269640  80000 dist/jquery.js
86921  30123 dist/jquery.min.js
raw     gz Compared to master @ b3defccdc0ca93b49647e79df5e70fb933af679c
+708   +209 dist/jquery.js
+139    +36 dist/jquery.min.js
```

Dimensions: Include scroll gutter in "padding" box

---

src/deferred.js

Fixes #3606
I'm not sure why we need both [callbacks and .then handlers](https://github.com/jquery/jquery/blob/00e0c7af79cf27b5c52f1f2dcb6770fd26d5119c/src/deferred.js#L56-L61). Could we instead merge those `Callback`s? EDIT: I think it's because error handling works different?

Deferred: fix memory leak of promise callbacks

---

src/offset.js
test/unit/offset.js

This adds tests verifying #3612. Could probably add more but this seemed to cover most cases?
Could potentially also revert 3befe5911af0cf516896482bb9ddf197c8cb8a8e

Test: ensure position/offset return mutable objects

---

src/css.js
src/css/support.js
test/unit/dimensions.js

Fixes gh-3699 with a new support property. But it's big, and the right call might just be to let this edge case fail:
```
270450  80204 dist/jquery.js
87101  30156 dist/jquery.min.js
raw     gz Compared to master @ 80f1c8239e9d5f793f3e54e0cb8d7bd0747e4856
+775   +190 dist/jquery.js
+198    +44 dist/jquery.min.js
```

Dimensions: Detect and account for content-box dimension mishandling

---

src/css.js
src/css/support.js
test/unit/dimensions.js
test/unit/support.js

Account for some IE9 quirks that were even stranger than first glance suggested, and add support assertions to fix broken tests.
Fixes gh-3699 (for real)
Fixes gh-3730
```
271034  80335 dist/jquery.js
87145  30139 dist/jquery.min.js
raw     gz Compared to master @ 3fcddd6e72e7e318c0b062e391d60867732318ae
+87    +16 dist/jquery.js
+34     +2 dist/jquery.min.js
```

Support: Properly check for IE9 absolute scrollbox mishandling

---

src/css.js
test/unit/dimensions.js

Recognize that offsetWidth and offsetHeight report CSS border-box dimensions, and (stealing gh-3602 from @timmywil) use them when Android lies about the size of inline elements.
Fixes gh-3698
Fixes gh-3602

Dimensions: Improve offsetWidth/offsetHeight fallback

---

src/css.js
test/unit/dimensions.js

Fixes gh-3611
Stops using non-pixel computed width/height values when calculating box sizes.

Dimensions: Don't trust non-pixel computed width/height

---

dist/.eslintrc.json

This fixes a small typo where "sizzle" is misspelled as "sizze" in a comment in an eslint config.

ESLint: Fix comment typo

---

test/jquery.js

Fixes #3756 by switching the path calculation from splitting at the first instance of "test", to finding its last index in the pathname, and then taking the substring from from the beginning until that index

Tests: update path calculation to split at last occurence of "test"

---

src/css/adjustCSS.js
test/unit/css.js
test/unit/effects.js

Because Firefox `getComputedStyle` reports post-calculation used values (and therefore arbitrarily high margin values all result in the same used value), we need to iterate towards something else when converting units.
Fixes gh-2144

CSS: Avoid unit-conversion interference from CSS upper bounds

---

build/tasks/lib/spawn_test.js
build/tasks/node_smoke_tests.js
build/tasks/promises_aplus_tests.js
package-lock.json
package.json

The first commit drops `cross-spawn` & uses the `child_process.spawn` shell option.
The second one increases the timeout used for Promises/A+ tests from 200 ms to 2 seconds. This should help with Jenkins failures.
I'd like to land it as two commits (unsquashed) as those are two separate changes, it was just easier to do the second one after the initial refactor.

Build: use child_process.spawn shell option, increase timeout in Promises/A+ tests 10 times

---

build/tasks/node_smoke_tests.js
build/tasks/promises_aplus_tests.js

This PR makes Node tests work for paths with spaces in them. Without this patch Jenkins tests fail as jQuery job names there contain spaces,
e.g. "jQuery Core".
I verified it works on Jenkins with this PR again.

Tests: Make Node tests work for paths with spaces in them

---

src/manipulation.js

Noticed in passing while investigating #3834.
```
271549  80440 dist/jquery.js
87285  30171 dist/jquery.min.js
raw     gz Compared to master @ 3e902a812014e8a6980e08599c4840b1cb969f7c
-37    -13 dist/jquery.js
+3     -6 dist/jquery.min.js
```

Manipulation: Reduce size by eliminating single-use variable

---

src/css/support.js
test/data/css/cssWidthBrowserZoom.html
test/unit/css.js

The pull request mainly has two tasks done:
- Test for the issue (#3808 )
- Fixing the issue by rounding off the measure to unit place.
However the test for the issue isn't working. I used an iframe test to check for the border-box width at `html {zoom: 1.1}`. Though opening the html file separately recreates the issue, but via the unittest code, it doesn't. 
Some help in fixing the unittest will be really helpful.

Fix the width calculation of border-box due to browser zoom

---

.travis.yml
package.json

Ref gh-3744
Only run browser tests in one Node version on Travis. This reduces the possibility of failure.

Build: Only run browser tests in one Node version on Travis

---

build/tasks/qunit_fixture.js

On Windows, the QUnit fixture HTML file has `\r\n` (CRLF) line endings when it's checked out into the directory by Git. This causes the built file to have CRLF as well, which generates spurious file diffs. I'm just removing the extra CRs in the file.
* [-] New tests have been added to show the fix or feature works
* [-] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

Build: Remove CRLF line endings to fix builds on Windows

---

test/unit/ajax.js

PR disables native abort test in Android 4.0.
The test works on its own when checked manually but mysteriously fails in
TestSwarm only in Android 4.0. Let's just disable it there.

Tests: Disable native abort test in Android 4.0

---

test/unit/deferred.js

It fixes Android 4.0 Deferred tests.

Tests: Fix Android 4.0 Deferred tests

---

src/css/curCSS.js
src/css/var/isHiddenWithinTree.js
src/manipulation.js
src/manipulation/buildFragment.js
src/var/isAttached.js

This change replaces the use of `jQuery.contains` to check for attachment of DOM
by `isAttached` function to better communicate what is being done.
Ref gh-3504

Core: Use isAttached to check for attachment of element

---

.travis.yml
Gruntfile.js

The Chrome sandbox doesn't work on Travis unless sudo is enabled. Instead,
we're disabling the Chrome sandbox.

Build: Don't require sudo on Travis, use sandboxless headless Chrome

---

src/css.js
src/css/finalPropName.js
src/effects/Tween.js

Fixes gh-3986
This avoids filling jQuery.cssProps by introducing a second internal
prop cache. It allows jQuery Migrate to detect external usage.

CSS: Avoid filling jQuery.cssProps

---

src/css.js

- this avoids forcing a reflow in some cases
Fixes #3991
```
raw     gz Compared to 3991 @ 625e19cd9be4898939a7c40dbeb2b17e40df9d54
+147    +63 dist/jquery.js
+12    +12 dist/jquery.min.js
```
Adds a bit of size but I think it's worth it...

Dimensions: avoid fetching boxSizing when setting width/height

---

src/event.js

Added the "code" property to the Event object passed to keyboard-triggered event handlers, as suggested on [#3978](https://github.com/jquery/jquery/issues/3978).

Changed event.js to add "code" property to keyboard event object

---

src/css/adjustCSS.js
test/unit/effects.js

Without this change animating properties from jQuery.cssNumber on non-elements
throws an error.
This came up while working on PR gh-4055.

CSS: Skip the px-appending logic for animations of non-element props

---

test/unit/css.js

This PR adds tests to ensure camel- vs kebab-cased names are not collapsed for CSS vars

CSS: Ensure camel- vs kebab-cased names are not collapsed for CSS vars

---

LICENSE.txt

Per gh-4039, the Github license identification algorithm is confused by our prolog and epilog to the MIT license. Although the license is defined as MIT in the `package.json` that doesn't seem to be enough of a hint. If this is okay with JSF legal I'd like to do it as the path of least resistance. Otherwise we'll need to lobby Github to be smarter with their license checker or just ignore it.

Misc: Update license prolog/epilog to placate Github checker

---

src/ajax/script.js
test/unit/ajax.js

Fixes gh-3028
Ref gh-2612
We've gotten a couple of tickets asking for a way to set attributes on script tags when they're injected as part of a `jQuery.ajax` request. Rather than defining a bunch of custom new ajax settings I thought it might be easier to just let the caller set any attribute on the script tag.  This would be useful, for example, to add `nonce`, `integrity`, or `crossorigin` attributes so that [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) will be appeased.
Possible todos that aren't in here yet, mainly because I wanted feedback:
- Add a `jQuery.getScript` signature
- I'm debating whether to assume crossDomain when attrs are given.

Ajax: Allow custom attributes when script transport is used

---

src/css.js
test/unit/css.js

CSS: Don't auto-append "px" to CSS variables

---

.github/lock.yml

Adds configuration for the bot described in https://github.com/apps/lock and gh-4069. In addition we'll need to add the bot to the repo's config.
I didn't add a close message because the bot will go through all the closed issues/PRs and lock them. If we add it now we'll get spammed with hundreds of messages. It would be possible to add some message after the bot has caught up, but be aware that all repo subscribers will see them.

Misc: Add config for lockbot

---

test/unit/css.js

In Edge 14-16 setting a style property to a whitespace-only value resets it to
the default, forcing us to skip a relevant CSS test in Edge. Now that Edge 17
has fixed the issue we can re-enable this test there.
Ref gh-3204

Test: enable a spec testing CSS whitespace preserving in Edge 17

---

src/core.js

The linked-to issue was fixed 2 years ago.
Removes an old eslint exception and comment explaining it

Remove unnecessary eslint exception

---

src/serialize.js
test/unit/serialize.js

Fixes https://github.com/jquery/jquery/issues/2633

Serialize: jQuery.param: return empty string when given null/undefined

---

src/css.js
test/unit/dimensions.js

Dimensions: fix computing outerWidth on SVGs

---

test/unit/support.js

Firefox 61 now passes the reliableMarginLeft test. This made our support tests fail.

Tests: Add support test results for Firefox 61+

---

src/core/var/rsingleTag.js
src/manipulation/var/rtagName.js
test/unit/manipulation.js

Updates `rtagName` to capture elements with single-character names (e.g., `<p>`), which were previously ignored.
Fixes gh-4124

 Manipulation: Properly detect HTML elements with single-character names

---

test/unit/manipulation.js

Edge sometimes doesn't execute module scripts. It needs to be investigated why
but for now we're skipping the test to make our tests more stable.

Tests: Skip module tests in Edge

---

test/unit/dimensions.js

The SVG `width` attribute seems to not support `border-box` in iOS7. This is not really relevant to what the test is for.
Closes gh-4155

Tests: use width style instead of SVG width attribute

---

Gruntfile.js
test/data/testinit.js
test/jquery.js
test/unit/ajax.js

Makes Karma behave more like the old tests by exposing a "load unminified" checkbox.

Tests: Allow Karma to load unminfied source

---

src/ajax.js
test/data/mock.php
test/middleware-mockserver.js
test/unit/ajax.js

This issue is described in more depth by #3403.
getResponseHeader(key) combines all header values for the provided key into a
single result where values are concatenated by ', '. This does not happen for
IE11 since multiple values for the same header are returned on separate lines.
This makes the function only return the last value of the header for IE11.

Fix getResponseHeader(key) for IE11

---

test/unit/dimensions.js

- Browsers differ on the default line-height for the element, which accounts for the variability across the failing browsers. The value we were getting from computed styles is exactly what we want: it's the real value that is reflected in the render even though the real browser height differs across browsers. The reason is that some browsers respect the line-height rather than the height style. Those that use line-height have a computed height/rendered height of line-height + padding + border. This sets a line-height of 18 so that the computed height still ends up being 30 for the assertion.

Tests: fix dimensions tests in testswarm

---

src/core.js

Read target[name] only when it's needed.
In addition to doing the property read only when needed, this avoids a slow path
in V8 (see issue for more details).
Fixes #4245

Core: Tiny efficiency fix to jQuery.extend / jQuery.fn.extend

---

src/manipulation/_evalUrl.js
test/unit/manipulation.js

Manipulation: Only evaluate HTTP-successful script src

---

src/manipulation/_evalUrl.js

IE and iOS \<10 XHR transport does not succeed on data: URIs
Ref gh-4243
Ref gh-4126

Manipulation: Always make _evalUrl requests as dataType: script

---

test/unit/ajax.js

Android Browser only returns the last value for each header so there's no way
for jQuery get all parts.
This commit skips the relevant assertion in Android Browser.
Ref gh-3403
Ref gh-4173

Tests: Exclude Android 4.x from repeated header names test

---

src/manipulation.js
test/data/inner_nomodule.js
test/data/nomodule.js
test/unit/manipulation.js

PR #3869 added support for `<script type="module">` & some support for
the `nomodule` attribute but with no tests for `nomodule` and with the
attribute only respected on inline scripts. This commit adds support for
source-based scripts as well. It also adds tests for `nomodule`, including
making sure legacy browsers execute such scripts as they'd natively do - that's
the whole point of `nomodule` scripts, after all.
Fixes gh-4281
Ref gh-3871
Ref gh-3869
* ~~If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~ - I don't think that's needed here.

Manipulation: Respect script nomodule attribute in DOM manipulation

---

src/core.js
src/core/DOMEval.js
src/manipulation.js
test/data/csp-nonce-globaleval.html
test/data/csp-nonce-globaleval.js
test/data/mock.php
test/middleware-mockserver.js
test/unit/manipulation.js

Support passing nonce through jQuery.globalEval:
```js
jQuery.globalEval( code, nonceValue );
```
Fixes gh-4278
Ref gh-3541
Ref gh-4269
Docs issue: https://github.com/jquery/api.jquery.com/issues/1123

Core: Support passing nonce through jQuery.globalEval

---

.github/ISSUE_TEMPLATE.md

JSFiddle doesn't support IE (even 11) anymore so we shouldn't advise users
to use it to create test cases. To make people have a choice, add CodePen
to the list.
Also, link to specific starter templates so that novices don't need to spend
time thinking how to set up the basic structure.

Build: Advise to create test cases on JS Bin or CodePen, drop JSFiddle

---

.travis.yml

Node.js 10 has been in Active LTS since 2018-04-24 and Node.js 8 is now in
maintenance mode.
See https://github.com/nodejs/Release for more details.

Build: Run Karma browser tests on Node.js 10 instead of 8

---

build/tasks/promises_aplus_tests.js

The default reporter is very verbose as it prints all the test names it
encounters. We already use the dot reporter for Karma tests.
This PR makes the Promises/A+ tests also use the dot reporter.

Build: Make Promises/A+ tests use the dot reporter instead of the default

---

src/css.js
test/unit/dimensions.js

This PR delays reading element `box-sizing` until it's necessary - either because of broken `box-sizing` handling or because we need that information for `extra` processing.
Fixes gh-4322
Ref gh-3991
Ref gh-4010
Ref gh-4185
Ref gh-4187

CSS: Avoid forcing a reflow in width/height getters unless necessary

---

src/core.js
test/unit/core.js

Prevent Object.prototype pollution for `$.extend( true, ... )`

Core: Prevent Object.prototype pollution for $.extend( true, ... )

---

src/event.js
test/unit/event.js

One commit to restore the test, one to fix it, and the rest to reduce size.
Ref 669f720edc4f557dfef986db747c09ebfaa16ef5
* Restore the no-duplication logic in focusin/focusout testing
* Reduce size
```
279073  82883 dist/jquery.js
88068  30594 dist/jquery.min.js
raw     gz Compared to master @ 669f720edc4f557dfef986db747c09ebfaa16ef5
+89   +209 dist/jquery.js
-113    -28 dist/jquery.min.js
```

Event: Cleanup leverageNative

---

src/manipulation.js
src/manipulation/_evalUrl.js
test/data/csp-nonce-external.html
test/data/csp-nonce-external.js
test/unit/manipulation.js

Fixes https://github.com/jquery/jquery/issues/4323

Core: Preserve CSP nonce on scripts with src attribute (#4323)

---

test/unit/ajax.js

Android Browser versions provided by BrowserStack fail the "prototype collision
(constructor)" test while locally fired emulators don't, even when they connect
to TestSwarm. Just skip the test there to avoid a red build.

Tests: Make Android Browser 4.0-4.3 AJAX tests green

---

test/unit/dimensions.js

Android Browser disregards td's box-sizing, treating it like it was content-box.
Unlike in IE, offsetHeight shares the same issue so there's no easy way to
workaround the issue without incurring high size penalty. Let's at least check
we get the size as the browser sees it.
Also, fix the nearby support comment syntax.

Tests: Make Android Browser 4.0-4.3 dimensions tests green

---

package.json
test/data/core/jquery-iterability-transpiled.html

core-js 3 no longer includes a built file in the bundle but core-js-bundle
does.

Tests: Fix the core-js polyfill inclusion method

---

src/css.js
src/css/adjustCSS.js
src/css/isAutoPx.js
src/effects/Tween.js
test/unit/css.js

Don't automatically add "px" to properties with a few exceptions
Fixes gh-2795
Ref gh-4009
This is an alternative to PR #4053.
Const over #4053:
- ~~it matches more than we theoretically want (the list in #4053 is precise), e.g. non-existent props like `top-width`~~
- it's a little slower than #4053 as it uses a regex instead of a simple property checking.
Pros over #4053:
- it only adds ~~1 byte~~ 6 bytes instead of 120

CSS: Don't automatically add "px" to properties with a few exceptions

---

src/.eslintrc.json
src/css/finalPropName.js

Also, prevent further similar breakages by changing our ESLint configuration
to disallow relying on a global jQuery object in AMD modules.
Fixes gh-4358

Build: Fix unresolved jQuery reference in finalPropName

---

src/event.js
test/unit/event.js

Prevent leftover saved data from async focus/blur from overriding outermost trigger handling.
Fixes gh-4350

Event: Fix handling of multiple async focus events

---

src/event.js

Prevents the addition of redundant dummy handlers for native-backed events.

Event: Prevent leverageNative from registering duplicate dummy handlers

---

src/core/isAttached.js
test/unit/css.js
test/unit/effects.js

The test for Shadow DOM v1 support has been changed to rely on the presence of
`documentElement.getRootNode` as iOS 10.0-10.2 supports `attachShadow` but
doesn't support `getRootNode`.
No new test is necessary - iOS 10.0 fails lots of our test suite because of
this bug.
Fixes gh-4356

Core: Make isAttached work with iOS 10.0-10.2

---

src/core/camelCase.js
src/css.js
src/css/cssCamelCase.js
src/deprecated.js
src/effects.js
test/unit/css.js
test/unit/data.js

The camelCase implementation used by the data module no longer turns `-ms-foo`
into `msFoo` but to `MsFoo` now. This is because `data` is supposed to be
a generic utility not specifically bound to CSS use cases.
Fixes gh-3355
`+2` bytes
* ~~If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~ (this behavior was never documented AFAIK)

Data: Separate data & css/effects camelCase implementations

---

src/css/curCSS.js
src/css/var/rboxStyle.js

A leftover `rboxStyle` was left in the wrapper parameters but not in the
dependency array, causing `getStyles` to be undefined in AMD mode.
Since `rboxStyle` is no longer used, it's now removed.
Ref gh-4347

Build: Fix AMD dependencies in curCSS

---

src/effects.js

Because of the above conditional, the 'type' variable has a value of type 'string' or undefined.
Therefore, boolean comparisons for 'type' variable is always unnecessary because it return true.
The patch removed the unnecessary conditional statement.
Fix https://github.com/jquery/jquery/issues/4374

Effect: Fix a unnecessary conditional statement in .stop()

---

src/traversing.js
test/unit/traversing.js

Fix for https://github.com/jquery/jquery/issues/4384
Since https://github.com/jquery/jquery/commit/0ba8e38d0c4ab4a4fb9054e7a713630be9743aff, using `contents()` to get the children of an `<object>` is not working.
Taking this example HTML
```html
<object type="application/x-shockwave-flash" width="200" height="300" id="penguin">
<param name="movie" value="flash/penguin.swf">
<param name="quality" value="high">
</object>
```
I'd expect the following to happen
```js
jQuery(objectHtml).contents().length // => 3
```
But what actually happens is:
```js
jQuery(objectHtml).contents().length // => 0
```
Changing the conditional to `elem.contentDocument != null` handles this case and the function returns the correct children.

Fix retrieving children of `<object>` using `contents()`

---

src/traversing.js

The original fix didn't account for the fact that in IE `<object>` elements
with no `data` attribute have an object `contentDocument`. The fix leverages
the fact that this special object has a null prototype.
Ref gh-4384
Ref gh-4385
+9 bytes. I tested it in IE this time.
* ~~New tests have been added to show the fix or feature works~~ Existing tests were failing before this PR.

Traversing: Fix `contents()` on `<object>`s with children in IE

---

build/tasks/build.js

Fix the regex parsing AMD var-modules.
The previous regex caused the final jQuery binary to have syntax errors for
var-modules with names starting with "return". For example, the following module
wouldn't work when the file is named `returnTrue.js`:
```js
define( function() {
"use strict";
return function returnTrue() {
return true;
};
} );
```
* ~~New tests have been added to show the fix or feature works~~ N/A
* ~~If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~ N/A

Build: Fix the regex parsing AMD var-modules

---

build/tasks/build.js
dist/.eslintrc.json
package.json
src/ajax.js
src/attributes/attr.js
src/core.js
src/core/access.js
src/core/camelCase.js
src/css.js
src/css/var/swap.js
src/deferred.js
src/deprecated.js
src/effects.js
src/event/ajax.js
src/event/alias.js
src/manipulation.js
src/offset.js
src/serialize.js
src/traversing.js

This commit requires all function parameters to be used, not just the last one.
In cases where that's not possible as we need to match an external API, there's
an escape hatch of prefixing an unused argument with `_`.
This change makes it easier to catch unused AMD dependencies and unused
parameters in internal functions the API of which we may change at will, among
other things.
Unused AMD dependencies have been removed as part of this commit.
What do you think? If you agree this change is worthwhile, should we add that rule to `eslint-config-jquery`?

Build: ESLint: forbid unused function parameters

---

src/selector-native.js
test/unit/core.js

Make selector-native's isXMLDoc recognize HTML-embedded SVG
This commit also backports some jQuery.isXMLDoc tests from master so that this
behavior doesn't regress.
(partially cherry-picked from 79b74e043a4ee737d44a95094ff1184e40bd5b16)
Ref jquery/sizzle#378
Ref jquery/sizzle#436

Selector: Make selector-native's isXMLDoc recognize HTML-embedded SVG

---

src/selector.js

Due to a faulty IE 8 workaround removal, the fast path qSA mode was skipped
when jQuery's find was called on an element node - i.e. in most cases. 😱
Ref gh-4395

Selector: Bring back querySelectorAll shortcut usage

---

test/data/testinit.js

#1435 # Summary ###
A copied comment line was accidentally left out above the line defining
`QUnit.jQuerySelectorsPos`, making the sentence nonsense. This commit removes
that line.
If there are more small fixes like that needed in various test files, we could wait with this PR to land them all in one batch.

Tests: Fix a comment in testinit.js

---

src/selector.js
src/selector/support.js
test/unit/selector.js
test/unit/support.js

The [`:scope` pseudo-class][1] has surprisingly good browser support: Chrome,
Firefox & Safari have supported if for a long time; only IE & Edge lack support.
This commit leverages this pseudo-class to get rid of the ID hack in most cases.
Adding a temporary ID may cause layout thrashing which was reported a few times
in [the past.
We can't completely eliminate the ID hack in modern browses as sibling selectors
require us to change context to the parent and then `:scope` stops applying to
what we'd like. But it'd still improve performance in the vast majority of
cases.
[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/:scope
Fixes gh-4453
Ref gh-4332
Ref jquery/sizzle#405
* ~~If needed, a docs issue/PR was created at …

Selector: Leverage the :scope pseudo-class where possible

---

src/core.js
src/deprecated.js
test/unit/basic.js
test/unit/core.js
test/unit/deprecated.js

Component: Core
- Moved `jQuery.trim()` from the `core.js` file into the `deprecated.js` file
- Moved corresponding unit test from `test/unit/core.js` to `test/unit/deprecated.js`
Fixes #4363

Core: Deprecate jQuery.trim

---

src/ajax/xhr.js

Previously, jQuery.ajaxSettings.xhr, contents were wrapped in a try-catch
as we defined jQuery.support.ajax & jQuery.support.cors executed during the
jQuery load and we didn't want to crash if IE had native XHR disabled (which
is possible). While jQuery hasn't supported the ActiveX-based XHR since 2.0,
jQuery with XHR disabled could still be used for its other features in such
a crippled browser.
Since gh-4347, jQuery.support.ajax & jQuery.support.cors no longer exist, so
we don't need the try-catch anymore.
Fixes gh-1967
Ref gh-4347
-8 bytes

Ajax: Simplify jQuery.ajaxSettings.xhr

---

test/unit/support.js

The regexes detecting browsers with their versions have been updated for iOS
and Safari so that all iOS >=11 & all Safari (desktop) >= 11 are recognized.
This is required to make Safari 13 & iOS 13 pass support tests but it'll also
make tests forward-compatible with future Safari/iOS versions.

Tests: Make support tests accept Safari 13 & newer

---

src/core.js
test/unit/core.js

Implement .even() & .odd() to replace POS :even & :odd. The current version adds 28 bytes; it'd be slightly smaller (+25 bytes) to rely on `.filter()` but that'd make `core` depend on `traversing/findFilter`.

Core: Implement .even() & .odd() to replace POS :even & :odd

---

src/core.js
src/selector.js
src/selector/uniqueSort.js
src/var/sort.js

Remove private copies of push, sort & splice from the jQuery prototype. Saves 13 bytes.

Core: Remove private copies of push, sort & splice from the jQuery prototype

---

src/selector.js

IE/Edge sometimes crash when comparing documents between frames using the strict
equality operator (`===` & `!==`). Funnily enough, shallow comparisons
(`==` & `!=`) work without crashing.
Fixes gh-4441
While I cannot be 100% certain this PR will solve the issue, I modified the code locally, wrapping the place where the browser crashes in a try-catch where I assigned both compared documents to global variables. I then compared them using all 4 operators manually in the console and the strict one were always crashing. I reproduced the same behavior in IE 11 & Edge 18.
I can't really write a test for it as the crashes are not consistent - the only consistent thing was that if it crashed once on a particular comparison, it keeps crashing on strict-comparing those two documents.
This fixes a …

Selector: Use shallow document comparisons to avoid IE/Edge crashes

---

build/release.js

File `src/core.js` has started erroneously being copied to `dist/` in gh-2981.
Fixes gh-4489
Ref gh-2979
Ref gh-2981

Build: Stop copying src/core.js to dist on release

---

README.md

`http://brew.sh/` >  `https://brew.sh/`
saves a HTTP redirect :-)

HTTPS link to Homebrew

---

.eslintrc-node.json
Gruntfile.js
build/release.js
build/release/cdn.js
build/release/dist.js
build/tasks/build.js
build/tasks/dist.js
build/tasks/node_smoke_tests.js
build/tasks/qunit_fixture.js
build/tasks/sourcemap.js
build/tasks/testswarm.js

So far, only browser-based JS files were required to be in strict mode (in the
function form). This commit adds such a requirement to Node.js scripts where
the global form is preferred. All Node.js scripts in sloppy mode were
converted to strict mode.

Build: Require strict mode in Node.js scripts via ESLint

---

src/selector.js

An optimization added in jquery/sizzle#431 skips the temporary IDs for selectors
not using child or descendant combinators. For sibling combinators, though, this
pushes a selector with a leading combinator to qSA directly which crashes and
falls back to a slower Sizzle route.
This commit makes selectors with leading combinators not skip the selector
rewriting. Note that after jquery/jquery#4454 & jquery/sizzle#453, all modern
browsers other than Edge leverage the :scope pseudo-class, avoiding temporary
id attributes.
Ref gh-431
+3 bytes
Sizzle PR (for jQuery 3.x): https://github.com/jquery/sizzle/pull/460
* ~~[ ] New tests have been added to show the fix or feature works~~ (we don't generally if a selector goes through `qSA`)
* ~~If needed, a docs issue/PR was created at …

Selector: Make selectors with leading combinators use qSA again

---

src/css.js
src/css/support.js
test/unit/css.js
test/unit/support.js

Workaround buggy getComputedStyle on table rows in IE/Edge.
Fixes gh-4490
This is a `master` version of #4503.

CSS: Workaround buggy getComputedStyle on table rows in IE/Edge

---

src/offset.js

An upcoming release of Migrate will generate warnings for calls to .css() that pass numbers rather than strings, see jquery/jquery-migrate#296 . At the moment, core's .offset() setter passes numbers rather than px strings so it would throw warnings.
This is the dumbest possible implementation I could think of (and `+18`) but there are several concerns I have with trying to optimize this code. First, there is an undocumented `using` option that is used by jQuery UI. Second, it's possible for options other than top and left to be passed through to .css() even though that's also undocumented; I don't know if anyone does that.
For the purposes of removing this warning for 3.x I want to just fix it so that Migrate can avoid spurious warnings, and not cause any other compat problems. For 4.x we …

Offset: Send px-ed strings to .css()

---

test/data/selector/mixed_sort.html
test/unit/selector.js

Stop using jQuery.find in tests. This prepares us for possibly hiding jQuery.find in jQuery 4.0.

Tests: Stop using jQuery.find in tests

---

test/unit/selector.js

Sizzle's PR jquery/sizzle#456 introduced a test catching not throwing on
badly-escaped identifiers by Firefox 3.6-5. Unfortunately, it was placed just
before a test Opera 10-11 failed, making Opera fail quicker and not adding
a post-comma invalid selector to rbuggyQSA.
The issue was fixed in jquery/sizzle#463. This jQuery commit backports the test
that Sizzle PR added as no workarounds are needed in browsers jQuery supports.
Ref jquery/sizzle#456
Ref jquery/sizzle#463

Selector: Add a test for throwing on post-comma invalid selectors

---

src/selector/uniqueSort.js

IE/Edge sometimes crash when comparing documents between frames using the strict
equality operator (`===` & `!==`). Funnily enough, shallow comparisons
(`==` & `!=`) work without crashing.
The change to shallow comparisons in `src/selector.js` was done in gh-4471 but
relevant changes in `src/selector/uniqueSort.js` were missed. Those changes
have landed in Sizzle in jquery/sizzle#459.
+1 byte
Fixes gh-4441
Ref gh-4471
Ref jquery/sizzle#459

Selector: Use shallow document comparisons in uniqueSort

---

.travis.yml
Gruntfile.js

Also, run them on both ChromeHeadless & FirefoxHeadless locally on
`grunt karma:main`.

Build: Run tests on Travis on FirefoxHeadless as well

---

Gruntfile.js

The environmental variable BROWSERS was being created but it wasn't read in the
list of browsers to pass to Karma.

Build: Run tests on Travis only on browsers defined in the config

---

test/unit/ajax.js

Chrome 78 dropped support for synchronous XHR requests inside of beforeunload, unload, pagehide, and visibilitychange event handlers. This made an AJAX test checking exactly that fail in Chrome.
See https://bugs.chromium.org/p/chromium/issues/detail?id=952452
BTW, I can't reliably reproduce the failure in Chrome on macOS when tested via the PHP setup. It does fail in Chrome 78 via Karma & in Edge Chromium in all ways, though. It also reliably fails in TestSwarm. Therefore, we need to drop that test in Chrome.

Tests: Don't test synchronous XHR on unload in Chrome

---

test/unit/dimensions.js

Tests: Skip a "width/height on a table row with phantom borders" test in Firefox
Firefox 70 & newer fail this test but the issue there is more profound - Firefox
doesn't subtract borders from table row computed widths.
Ref jquery/jquery#4529
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1590837
Ref w3c/csswg-drafts#4444

Tests: Skip a "width/height on a table row with phantom borders" test in Firefox

---

package.json
src/.eslintrc.json

jQuery source is now authored in ECMAScript modules. Native browser support for
them requires full file names including extensions. Rollup works even if import
paths don't specify extensions, though, so one import slipped through without
such an extension, breaking native browser import of src/jquery.js.
A new ESLint rule using eslint-plugin-import prevents us from regressing on that
front.
Ref gh-4541
Ref 075320149ae30a5c593c06b2fb015bdf033e0acf
EDIT: Also, make sure we don't have import cycles in src/
eslint-plugin-import's no-cycle rule is used for cycle detection.

Build: Require extensions for ES6 imports, prevent import cycles

---

build/tasks/build.js
build/tasks/lib/rollup-plugin-file-overrides.js
package.json

This PR gets rid of rollup-plugin-hypothetical in favor of a simpler
inline Rollup plugin that fits our need and is compatible with Windows.
Fixes gh-4548
@wangwanchao @dmethvin can you check if that solves your issues?

Build: Fix the Windows build

---

README.md

MacOS has been around for long enough to update the naming here.

Docs: Change OS X to macOS in README

---

src/event.js
test/unit/event.js

There was a check in jQuery.event.add that was supposed to make it a noop
for objects that don't accept data like text or comment nodes. The problem was
the check was incorrect: it assumed `dataPriv.get( elem )` returns a falsy
value for an `elem` that doesn't accept data but that's not the case - we get
an empty object then. The check was changed to use `acceptData` directly.
Fixes gh-4397
It's funny that this has been the behavior for at least the past few years so this code has been wrong for a long time. 😱 
We'll also need to CP that to `3.x-stable`
+2 bytes

Event: Only attach events to objects that accept data - for real

---

.travis.yml
Gruntfile.js
package.json
test/data/testinit-jsdom.js
test/data/testinit.js
test/index.html
test/jquery.js
test/karma.context.html
test/karma.debug.html
test/unit/selector.js

Make Karma work in ES modules mode
Also, run such a suite in CI to make sure modules are working as expected
when used directly.
We could consider doing a version of this PR for AMD for 3.x-stable, I don't see any fundamental roadblocks.

Build: Make Karma work in ES modules mode

---

README.md

Link to GH docs for cloning a repo.

Docs: direct users to GitHub docs for cloning the repo

---

src/selector/rbuggyQSA.js
test/unit/selector.js

Remove the workaround for a broken `:enabled` pseudo-class on anchor elements
in Chrome <=77. These versions of Chrome considers anchor elements with the
`href` attribute as matching `:enabled`.
-23 bytes gzipped
* ~~New tests have been added to show the fix or feature works~~ (this is already tested)

Selector: Remove the "a:enabled" workaround for Chrome <=77

---

README.md
build/release.js
build/tasks/build.js

This PR adds a custom `slim` alias for the official Slim build. It will allow to achieve the same build locally in an easier way and will also de-duplicate the slim build configuration in changes like #4577, making us sure we really test the slim build even after its definition changes.
This PR interferes with #4577 so whichever one lands first, the other one will need to get updated (e.g. if #4577 lands first, this PR will need to modify the new Travis config to use the new alias).

Build: Create a `grunt custom:slim` alias for the Slim build

---

test/unit/support.js

The check for old Firefox versions with different support test result only
checked for Firefox 52 or 60. It now checks for 4x/5x/60 to understand more
versions.
This is needed for our unofficial Firefox 48 testing on `3.x-stable`.

Tests: Make the support tests pass on Firefox 4x/5x/60

---

Gruntfile.js
test/jquery.js

PR gh-4550 added support for running ES modules & AMD tests via Karma. This
required reading the `esmodules` & `amd` props from both `QUnit.config` &
`QUnit.urlParams`. By picking these two properties manually, the `dev` one
stopped being respected while ones handled directly by QUnit were fine (like
`hidepassed`). Instead of maintaining the full list of options, the code now
iterates over QUnit URL config and handles the fallbacks in a more generic way.
Apart from that, all jQuery source & test files are now read directly from disk
instead of being cached by Karma so that one can run `grunt karma:chrome-debug`
& work on a fix without restarting that Karma run after each change. A similar
effect could have been achieved by setting `autoWatch` to `true` but then the
main Karma page runs …

Build: Make dev mode work in Karma again, serve source files from disk

---

src/attributes/attr.js

This removes a needless function call in modern browsers.
+3 bytes

Attributes: Don't set the type attr hook at all outside of IE

---

test/data/testrunner.js
test/unit/attributes.js
test/unit/data.js
test/unit/effects.js

Remove obsolete jQuery data tests.
The tests relied on `jQuery.cache` so they only ever worked in jQuery 1.x.

Tests: Remove obsolete jQuery data tests

---

src/attributes/val.js
test/unit/attributes.js

Before this change, `val()` was stripping out carriage return characters from
the returned value. No test has relied on that. The logic was different for
option elements as its custom defined hook was omitting this stripping logic.
This commit gets rid of the carriage return removal and isolates the IE-only
select val getter to be skipped in other browsers.
-16 bytes

Attributes: Refactor val(): don't strip carriage return, isolate IE workarounds

---

build/tasks/build.js

So far, the slim build only excluded ajax & effects modules. As many web apps
right now rely on native Promises, often with a polyfill for legacy browsers,
deferred & callbacks modules are not that useful for sites that already exclude
ajax & effects modules.
This decreases the gzipped minified size of the slim module by 1758 bytes,
to 19656 bytes (below 20k!).

Core: Exclude callbacks & deferred modules in the slim build as well

---

.travis.yml
Gruntfile.js
package.json
test/data/testinit-jsdom.js
test/data/testinit.js
test/index.html
test/jquery.js
test/karma.context.html
test/karma.debug.html

This is a backport of gh-4550 & gh-4574 to `3.x-stable`.
Also, run such a suite in CI to make sure modules are working as expected
when used directly.
(partially cherry picked from 341c6d1b5abe4829f59fbc32e93f6a6a1afb900f)
(partially cherry picked from 437f389a24a6bef213d4df507909e7e69062300b)
Ref gh-4550
Ref gh-4574

Build: Make Karma work in AMD mode

---

Gruntfile.js

Code in gh-4594 configured ESLint properly but didn't change the Gruntfile.js
config to actually lint the minified file. This has now been fixed.
Fixes gh-3075
Ref gh-4594

Build: Lint the minified jQuery file as well - a Gruntfile fix

---

README.md

The file contents now lie in deprecated/event.js so the README reference
is no longer correct.
Ref gh-4572

Docs: Remove a mention of the event/alias.js module from README

---

src/event.js
test/data/testrunner.js

jQuery.event.global has been write-only in the jQuery source for the past few
years; reading from it was removed in c2d6847de09a52496f78baebc04f317e11ece6d2
when fixing the trac-12989 bug.

Event: remove jQuery.event.global

---

src/core.js
src/manipulation.js
src/manipulation/_evalUrl.js
test/data/core/globaleval-context.html
test/data/manipulation/set-global-scripttest.js
test/data/testinit.js
test/unit/core.js
test/unit/manipulation.js

1. Support passing custom document to jQuery.globalEval; the script will be
invoked in the context of this document.
2. Fire external scripts appended to iframe contents in that iframe context;
this was already supported & tested for inline scripts but not for external
ones.
Fixes gh-4518

Core: Fire iframe script in its context, add doc param in globalEval

---

src/ajax.js
src/ajax/jsonp.js
src/ajax/var/nonce.js
src/exports/global.js

This PR aligns the `3.x-stable` branch with `master` in two aspects:
1. It migrates the nonce module to return an object instead of a primitive
variable. This had to be changed on `master` as in ES modules you export
live read-only bindings to variables, meaning you can't increment the nonce
directly. Also, the way it was done so far was working differently in AMD & the
single built file - in the built file one nonce variable was declared, accessed
and incremented. In AMD mode separate instances were create for each module
that depend on the nonce module, creating unintended nonce clashes.
2. Whether the `noGlobal` parameter was set to `true` is now checked using the
typeof operator to align with `master`.
+8 bytes
* ~~If needed, a docs issue/PR was created at …

Core:Ajax: Align nonce & global with master, fix an AMD issue

---

test/unit/basic.js
test/unit/ready.js

It is no longer needed to create `done` wrappers in tests that require multiple
async operations to complete.

Tests: Pass a number of necessary done() calls to assert.async()

---

.eslintrc-browser.json
dist/.eslintrc.json
src/css/support.js
src/event.js
test/.eslintrc.json

Node.js code is written more & more commonly in ES6+ so it doesn't make sense
to enable it there. There are many violations in test code so it's disabled
there as well.

Build: Enable ESLint one-var rule for var declarations in browser code

---

build/fixtures/README.md
build/release.js
build/release/dist.js

Use a dist README fixture kept in the jQuery repository instead of modifying
an existing one. This makes the jQuery repository the single source of truth
when it comes to jQuery releases and it makes it easier to make changes to
README without worrying how it will affect older jQuery lines.
https://github.com/jquery/jquery-release/pull/103 is a pre-requisite to make this PR work.

Release: Use an in-repository dist README fixture

---

src/data/Data.js
src/event.js
src/event/trigger.js
src/manipulation.js
test/unit/data.js
test/unit/event.js

Make sure events & data keys matching Object.prototype properties work.
A separate fix for such events on cloned elements was added as well.
The commit also removes two unnecessary checks:
1. A check for `events` in private data in `.trigger()` - only the `handle`
key is needed.
2. A fallback of the `events` private data to an empty object in
`jQuery.event.dispatch` because that method is called from the `handle`
function in element's private data and both `events` & `handle` are set and
removed at the same time.
Fixes gh-3256

Data:Event:Manipulation: Prevent collisions with Object.prototype properties

---

.travis.yml

Travis reports warnings in our config:
* root: deprecated key sudo (The key `sudo` has no effect anymore.)
* root: missing os, using the default linux
* root: key matrix is an alias for jobs, using jobs
They are all now resolved.

Build: Resolve Travis config warnings

---

src/manipulation.js
test/data/testinit.js
test/localfile.html
test/unit/ajax.js
test/unit/attributes.js
test/unit/basic.js
test/unit/core.js
test/unit/css.js
test/unit/data.js
test/unit/deprecated.js
test/unit/dimensions.js
test/unit/effects.js
test/unit/event.js
test/unit/manipulation.js
test/unit/offset.js
test/unit/selector.js
test/unit/traversing.js
test/unit/wrap.js

Make tests pass with jQuery.htmlPrefilter being an identity function.

Manipulation: Make jQuery.htmlPrefilter an identity function

---

src/event/focusin.js
test/unit/event.js

The `doc` variable in:
https://github.com/jquery/jquery/blob/3.4.1/src/event/focusin.js#L30
matched `document` for `document` & `window` for `window`, creating two separate
wrapper event handlers & calling handlers twice if at least one `focusout` or
`focusin` handler was attached on *both* `window` & `document`, or on `window`
& another regular node.
Also, fix the "focusin from an iframe" test to actually verify the behavior
from commit 1cecf64e5aa415367a7dae0b55c2dd17b591442d - the commit that
introduced the regression - to make sure we don't regress on either front.
+5 bytes.
Test updates should be cherry-picked to `master` without any source changes.

Event: Use only one focusin/out handler per matching window & document

---

src/ajax.js
test/unit/ajax.js

Overwrite s.contentType with content-type header value, if any
Fixes #4119

Ajax: Overwrite s.contentType with content-type header value, if any

---

src/data/Data.js
test/unit/data.js

Make the data object a regular object again.
The change in gh-4603 made the object returned by `elem.data()` a prototype-less
object. That's a desired change to support keys colliding with Object.prototype
properties but it's also a breaking change so it has to wait for jQuery 4.0.0.
A 3.x-only test was added to avoid breaking it in the future on this branch.
Fixes gh-4665
Ref gh-4603
-1 byte

Data: Make the data object a regular object again

---

.eslintrc-browser.json
.eslintrc-node.json
Gruntfile.js

The reportUnusedDisableDirectives option in ESLint will report an error when in inline disable directive is no longer required, such as what happened gh-4095.

Build: Enable reportUnusedDisableDirectives in ESLint

---

test/middleware-mockserver.js

The "jQuery.ajax() - JSONP - Same Domain" test is firing a request with
a duplicate "callback" parameter, something like (simplified):
```
mock.php?action=jsonp&callback=jQuery_1&callback=jQuery_2
```
There was a difference in how the PHP & Node.js implementations of the jsonp
action in the mock server handled situations like that. The PHP implementation
was using the latest parameter while the Node.js one was turning it into an
array but the code didn't handle this situation. Because of how JavaScript
stringifies arrays, while the PHP implementation injected the following code:
```js
jQuery_2(payload)
```
the Node.js one was injecting the following one:
```js
jQuery_1,jQuery_2(payload)
```
This is a comma expression in JavaScript; it so turned out that in the majority
of cases both …

Tests: Fix flakiness in the "jQuery.ajax() - JSONP - Same Domain" test

---

dist/.eslintrc.json
src/core.js

This disable-directive only applies to the built version, so put it in /dist. This avoids a warning about an unused directive in the source version.
Follow-up to #4520

Build: Move ESLint max-len disable-directive to dist/.eslintrc.json

---

test/unit/event.js

Backport tests from a jQuery 3.x fix that's not needed on `master`.
Also, fix the "focusin from an iframe" test to actually verify the behavior
from commit 1cecf64e5aa415367a7dae0b55c2dd17b591442d - the commit that
introduced the regression - to make sure we don't regress on either front.
The main part of the modified test was checking that focusin handling in an
iframe works and that's still checked. The test was also checking that it
doesn't propagate to the parent document, though, and, apparently, in IE it
does. This one test is now blacklisted in IE.
(cherry picked from 9e15d6b469556eccfa607c5ecf53b20c84529125)
(cherry picked from 1a4f10ddc37c34c6dc3a451ee451b5c6cf367399)
Ref gh-4652
Ref gh-4656

Tests: Use only one focusin/out handler per matching window & document

---

build/tasks/build.js

So far, the slim build was expanded to its full exclusion list, generating the
following `jQuery.fn.jquery`:
```
v4.0.0-pre -ajax,-ajax/jsonp,-ajax/load,-ajax/script,-ajax/var/location,-ajax/var/nonce,-ajax/var/rquery,-ajax/xhr,-manipulation/_evalUrl,-deprecated/ajax-event-alias,-callbacks,-deferred,-deferred/exceptionHook,-effects,-effects/Tween,-effects/animatedSelector,-queue,-queue/delay,-core/ready
```
This PR changes it to just `v4.0.0-pre slim`. Only the pure slim build is
treated this way, any modification to it goes through the old expansion; e.g.
for `custom:slim,-deprecated` we get the following `jQuery.fn.jquery`:
```
v4.0.0-pre -deprecated,-deprecated/ajax-event-alias,-deprecated/event,-ajax,-ajax/jsonp,-ajax/load,-ajax/script,-ajax/var/location,-ajax/var/nonce,-ajax/var/rquer …
```

Build: Reduce the slim build header comment & jQuery.fn.jquery

---

test/unit/manipulation.js

iOS 8-12 parses `<noembed>` tags differently, executing this code. This is no
different to native behavior on that OS, though, so just accept it.
Ref gh-4685

Tests: Workaround failures in recent XSS tests in iOS 8 - 12

---

src/jquery.js
test/unit/css.js

The `show()`, `hide()` & `toggle()` methods were included in the 3.x jQuery slim
build. The jQuery master build accidentally started to exclude them as they were
only imported in the effects module and the new Rollup-based build system
follows the module dependency graph when excluding modules.
To resolve the issue, import the `css/showHide.js` file directly in the main
`jquery.js` file.
We don't really have tests for what gets into the slim build so I didn't add anything.

CSS: Include `show`, `hide` & `toggle` methods in the jQuery slim build

---

.eslintrc.json
Gruntfile.js
build/tasks/amd.js
build/tasks/build.js
src/.eslintrc.json
src/ajax.js

This PR cleans up a few comments & configurations that are out of date
after the migration to ES modules backed by a Rollup-based compilation.
Also, de-indent AMD modules. This will preserve a more similar
structure to the one on 3.x-stable where the body of the main `define`
wrapper is not indented.

Build: Followups after introducing ES modules compiled via Rollup

---

test/data/testrunner.js
test/unit/wrap.js

Tests: Remove remaining obsolete jQuery.cache references
PR gh-4586 removed some of those but not all.
Ref gh-4586

Tests: Remove remaining obsolete jQuery.cache references

---

src/deprecated.js
src/var/trim.js
test/unit/deprecated.js

The API has been deprecated in 3.5.0 so it can be removed in 4.0.0.
Ref gh-4461

Deprecated: Remove jQuery.trim

---

src/.eslintrc.json
src/core/init.js
src/core/parseXML.js
src/core/var/rhtml.js
src/event/trigger.js
src/jquery.js
src/manipulation/_evalUrl.js

Make sure all source modules' exports are used.
To achieve that, use `eslint-plugin-import`'s `no-unused-modules` rule.
Also, explicitly import `event/trigger.js` from `jquery.js`; so far it was only
imported from ajax.js, making it mistakenly skipped in the
`custom:slim,-deprecated` build.
-5 bytes! :)

Build:Event: Make sure all source modules' exports are used

---

.github/ISSUE_TEMPLATE.md

The issue about selectors with '#' being broken is old and no longer frequently
reported so this commit removes it from the list. On the other hand, we're now
getting lots of reports about the security fix in jQuery 3.5.0 that was also
a breaking change: gh-4642. This one is now mentioned in the list.
Ref gh-4642

Docs: Update Frequently Reported Issues in the GitHub issue template

---

package.json

Fixes gh-4735
As  defined in [commitplease README](https://github.com/jzaefferer/commitplease/blob/master/README.md):
Changed hook `commit-msg` to `commitplease .git/COMMIT_EDITMSG`
Signed-off-by: Beatriz Rezener <beatrizrezener@gmail.com>

Build: Fix commitplease husky config

---

src/offset.js

The way warning against number values in `.css()` setters was done in
jquery/jquery-migrate#337 and later refined in jquery/jquery-migrate#348
there's no need to send px-ed strings for `top` & `left` as they already
don't get the "px" suffix.
This reverts commit 57038faebc6ece5bd666c28303f8a91ff59153eb.
Ref jquery/jquery-migrate/pull/337
Ref jquery/jquery-migrate/pull/348

Revert "Offset: Send px-ed strings to .css()"

---

src/ajax/jsonp.js
test/data/json.json
test/data/mock.php
test/middleware-mockserver.js
test/unit/ajax.js

Previously, `jQuery.ajax` with `dataType: 'json'` with a provided callback was
automatically converted to a jsonp request unless one also specified
`jsonp: false`. Today the preferred way of interacting with a cross-domain
backend is CORS which works in all browsers jQuery 4 will support.
Auto-promoting JSON requests to JSONP ones introduces a security issue as the
developer may be unaware they're not just downloading data but executing code
from a remote domain.
This commit disables the auto-promoting logic.
BREAKING CHANGE: to trigger a JSONP request, it's now required to specify
`dataType: "jsonp"`; previously some requests with `dataType: "json"` were
auto-promoted to JSONP.
Fixes gh-1799
Fixes gh-3376

Ajax: Drop the json to jsonp auto-promotion logic

---

src/var/isFunction.js

Fix allows jQuery to recognize that DOM types such as HTMLCollection or NodeList are not functions.
Fixes gh-4756

Core: Bring back QtWebKit support for jQuery 3.x

---

src/ajax/script.js
test/data/csp-ajax-script-downloaded.js
test/data/csp-ajax-script.html
test/data/csp-ajax-script.js
test/data/mock.php
test/middleware-mockserver.js
test/unit/ajax.js

Until now, the AJAX script transport only used a script tag to load scripts
for cross-domain requests or ones with `scriptAttrs` set. This commit makes
it also used for all async requests to avoid CSP errors arising from usage
of inline scripts. This also makes `jQuery.getScript` not trigger CSP errors
as it uses the AJAX script transport under the hood.
For sync requests such a change is impossible and that's what `jQuery._evalUrl`
uses. Fixing that is tracked in gh-1895.
The commit also makes other type of requests using the script tag version of the
script transport set its type to "GET", namely async scripts & ones with
`scriptAttrs` set in addition to the existing cross-domain ones.
Fixes gh-3969

Ajax: Avoid CSP errors in the script transport for async requests

---

src/ajax.js
test/data/mock.php
test/unit/ajax.js

Fixes: #4771 
However, it should not parse the response if just a script

Ajax: Execute JSONP error script responses

---

src/event.js

All supported browsers implement this property by themselves. The shim was only
needed for IE <9.
Fixes gh-3235
Ref gh-4755
-101 bytes!

Event: Remove the event.which shim

---

src/attributes/classes.js
test/unit/attributes.js

Attributes: Drop the `toggleClass(boolean|undefined)` signature.
The behavior of this signature is not intuitive, especially if classes are
manipulated via other ways between `toggleClass` calls.
Fixes gh-3388
-86 bytes
* ~~New tests have been added to show the fix or feature works~~ (tests have been removed)

Attributes: Drop the `toggleClass(boolean|undefined)` signature

---

src/.eslintrc.json

When run via WebStorm, the root path against which paths in the config of the
`import/no-unused-modules` ESLint rule are resolved is the path where the ESLint
config file that defines the rule lies, i.e. `src`. When run via the command
line, it's usually the root folder of the jQuery repository. This pattern
intends to catch both.
Note that we cannot specify two patterns here:
```js
[ "src/*.js", "*.js" ]
```
as they're analyzed individually and the rule crashes if a pattern cannot be
matched.

Build: Make the import/no-unused-modules ESLint rule work in WebStorm

---

test/unit/ajax.js

The test has been already skipped in Chrome as it dropped support for such
requests and now Safari has joined the squad.
This will resolve AJAX test errors we've had for a while in Safari 13 & iOS 13.

Tests: Skip the "jQuery.ajax() on unload" test in Safari

---

test/middleware-mockserver.js

This aligns the Node.js server with the previous PHP one in accepting `mock.php`
as a callback which is triggered by a recently added test. This prevents the
request crashing on that Node.js server and printing a JS error:
```
TypeError: Cannot read property '1' of null
```
Ref gh-4754

Tests: Recognize callbacks with dots in the Node.js mock server

---

build/tasks/build.js

The queue module is not present in the slim build as it depends on deferred
and our Gruntfile specifies excluding deferred should also exclude queue:
https://github.com/jquery/jquery/blob/3.5.1/Gruntfile.js#L66
This commit makes this exclusion explicit so that the queue module never
accidentally gets re-included in the slim build if it stopped importing from
the deferred module directly.

Build: Explicitly exclude the queue module from the slim build

---

src/event.js
test/unit/event.js

In Chrome, if an element having a focusout handler is blurred by
clicking outside of it, it invokes the handler synchronously. If
that handler calls `.remove()` on the element, the data is cleared,
leaving private data undefined. We're reading a property from that
data so we need to guard against this.
Fixes gh-4417

Event: Don't crash if an element is removed on blur

---

.travis.yml

Test on Node.js 15. Also, run browser tests on Node 14 instead of 12.

Build: Test on Node.js 15

---

src/event.js
test/unit/event.js

If during a focus handler another focus event is triggered:
```js
elem1.on( "focus", function() {
elem2.trigger( "focus" );
} );
```
due to their synchronous nature everywhere outside of IE the hack added in
gh-4279 to leverage native events causes the native `.focus()` method to be
called last for the initial element, making it steal the focus back. To resolve
this, we now skip calling the native method if focus was changed.
A side effect of this change is that now `focusin` will only propagate to the
document for the last focused element. This is a change in behavior but it also
aligns us better with how this works with native methods.
Fixes gh-4382
Ref gh-4279

Event: Make focus re-triggering not focus the original element back

---

src/core.js
test/unit/core.js

Fixes gh-4782
Sizzle version for jQuery 3.x: https://github.com/jquery/sizzle/pull/474.

Core: Make jQuery.isXMLDoc accept falsy input

---

src/core/parseXML.js
test/unit/core.js

Fixes gh-4784
In IE 11 we'd just throw an empty error now, in others - the reported error. We wouldn't include input data in the thrown error anymore.
+10 bytes, although I cheated a bit - I also removed an assignment of `xml` to `undefined` in `catch` as any error would happen before the assignment so the variable would already hold the `undefined` value. Without this optimization, it'd be +13 bytes.
That +10 can be changed to -3 if we just call:
```js
jQuery.error( parserErrorElem && parserErrorElem.textContent )
```
but that has two issues. Here's the returned element `parsererror` (after pretty-printing) in Blink & WebKit:
```xml
<parsererror
xmlns="http://www.w3.org/1999/xhtml"
style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; …
```

Core: Report browser errors in parseXML

---

src/css.js
src/css/support.js
test/unit/dimensions.js
test/unit/support.js

Fixes gh-4529
Firefox incorrectly (or perhaps correctly) includes table borders in computed
dimensions, but they are the only one. Workaround this by testing for it and
falling back to offset properties.
This applies to latest FF and so needs to go on master as well.
+203 bytes

Dimensions: Add offset prop fallback to FF for unreliable TR dimensions

---

src/css/support.js
test/unit/dimensions.js
test/unit/support.js

Fixes gh-4529
Firefox incorrectly (or perhaps [correctly](https://github.com/w3c/csswg-drafts/issues/4444)) includes table borders in computed
dimensions, but they are the only one. Workaround this by testing for it and
falling back to offset properties
+47 bytes currently

Dimensions: Modify reliableTrDimensions support test to account for FF

---

test/middleware-mockserver.js
test/unit/ajax.js

Two issues are fixed in testing for responses with a script Content-Type not
getting auto-executed unless an explicit `dataType: "script"` is provided:
* the test is now using a correct "text/javascript" Content-Type; it was using
"text/html" until now which doesn't really check if the fix works
* the Node.js based version of the tests didn't account for an empty `header`
query string parameter
Ref gh-2432
Ref gh-2588
Ref 39cdb8c9aa0fde68f733553ba050a2ba9d86474c

Tests: Fix tests for not auto-executing scripts without dataType

---

src/deferred.js

Rename a few occurrences of the word `master` to `primary` in deferreds.

Deferred: Rename master to primary

---

src/ajax/script.js
test/unit/ajax.js

Ajax: Don't auto-execute scripts unless dataType provided
PR gh-2588 made jQuery stop auto-execute cross-domain scripts unless
`dataType: "script"` was explicitly provided; this change landed in jQuery
3.0.0. This change extends that logic same-domain scripts as well.
After this change, to request a script under a provided URL to be evaluated,
you need to provide `dataType: "script` in `jQuery.ajax` options or to use
`jQuery.getScript`.
Fixes gh-4822
Ref gh-2432
Ref gh-2588
-28 bytes

Ajax: Don't auto-execute scripts unless dataType provided

---

src/css/support.js

- Fixes an issue with the support test in iframes in Android 8 Chrome 86+,
where display: inline resulted in unexpected height values.
Fixes gh-4832
This PR fixes a support test failure in Chrome on Android 8.

Support: ensure display is set to block for the support div

---

.eslintignore
.gitignore
.npmignore
Gruntfile.js
package.json
test/index.html
test/karma.debug.html

In gh-4466, we removed the `external` directory in favor of loading some files
directly from `node_modules`. This works fine locally but when deploying code
for tests, this makes it impossible to not deploy `node_modules` as well. To
avoid the issue, this change restores usage of the `external` directory.
One change is that we no longer commit this directory to the repository, its
only purpose is to have clear isolation from `node_modules`.
Ref gh-4466

Build: Restore the external directory

---

Gruntfile.js
test/data/core/jquery-iterability-transpiled.html

Build: Take core-js-bundle from the external directory as well
That package was missed in gh-4865 as it only broke browsers needing the
polyfill which is just IE at the moment. Thus, it broke Core tests in IE only.
Ref gh-4865

Build: Take core-js-bundle from the external directory as well

---

test/unit/selector.js

Chrome & Firefox now support complex `:not()` selectors so those test can run
in them even without custom jQuery selector code. In the past, it was only
possible in Safari, now we only need to exclude IE.

Tests: Make more tests run natively in Chrome & Firefox

---

test/data/mock.php
test/middleware-mockserver.js

Strip untypical callback parameter characters from mock.php.
Only allow alphanumeric characters & underscores for callback parameters.
The change is done both for the PHP server as well as the Node.js-based version.
This is only test code so we're not fixing any security issue but it happens
often enough that the whole jQuery repository directory structure is deployed
onto the server with PHP enabled that it makes is easy to introduce security
issues if this cleanup is not done.
Ref gh-4764
I'd like to also merge a version of this to the `2.2-stable` & `1.12-stable` branches as the `jsonp.php` file has the same issues as `mock.php` with some `action` parameters.
* ~~If needed, a docs issue/PR was created at …

Tests: Strip untypical callback parameter characters from mock.php

---

.travis.yml
test/data/jsonp.php
test/data/with_fries_over_jsonp.php
test/unit/ajax.js
test/unit/support.js

Only allow alphanumeric characters & underscores for callback parameters.
This is only test code so we're not fixing any security issue but it happens
often enough that the whole jQuery repository directory structure is deployed
onto the server with PHP enabled that it makes is easy to introduce security
issues if this cleanup is not done.
This is a 1.x/2.x version of PR gh-4871.
The change doesn't require a release; it's meant at installations testing
the latest state of `1.12-stable` & `2.2-stable` branches.
This change also fixes testing on Travis & on Chrome/Firefox.
Ref gh-4764
Ref gh-4871

Tests: Strip untypical callback parameter characters from PHP files

---

src/event.js
test/unit/event.js

The `_default` function in the special event settings for focus/blur has
always returned `true` since gh-4813 as the event was already being fired
from `leverageNative`. However, that only works if there's an active handler
on that element; this made a quick consecutive call:
```js
elem.on( "focus", function() {} ).off( "focus" );
```
make subsequent `.trigger( "focus" )` calls to not do any triggering.
The solution, already used in a similar `_default` method for the `click` event,
is to check for the `dataPriv` entry on the element for the focus event
(similarly for blur).
Fixes gh-4867
+10 bytes

Event: Don't break focus triggering after `.on(focus).off(focus)`

---

test/data/testsuite.css
test/unit/css.js

Avoids noise from unexpected third-party pings during development (Little Snitch popped up unexpectedly asking for this legacy CDN hostname), and avoids console noise when testing/developing jQuery offline.

Tests: Switch background image from online file to local 1x1.jpg

---

src/manipulation.js
test/data/cleanScript.html
test/unit/manipulation.js

When evaluating scripts, jQuery strips out the possible wrapping HTML comment
and a CDATA section. However, all supported browsers are already doing that
when loading JS via appending a script tag to the DOM which is how we've been
doing `jQuery.globalEval` since jQuery 3.0.0. jQuery logic was imperfect, e.g.
it just stripped the `` markers, respectively at the beginning or
the end of the script contents. However, browsers are also stripping everything
following those markers in the same line, treating them as single-line comments
delimiters; this is now also mandated by ECMAScript 2015 in Annex B. Instead
of fixing the jQuery logic, just let the browser do its thing.
We also used to strip CDATA sections. However, this shouldn't be needed as in
XML documents they're already not visible …

Manipulation: Don't remove HTML comments from scripts

---

test/data/mock.php

For some reason the current setup worked fine with Apache but broke for me when
I migrated to nginx.
@Krinkle was there any reason for this `unlink` call?

Tests: Don't remove csp.log in the cspClean action of mock.php

---

Gruntfile.js

Since the default Karma browser no activity timeout was lower than the QUnit
timeout, a single timing out test was interrupting the whole test run of
a browser.
The QUnit timeout is set to 1 minute so I set the Karma one to 2 minutes.

Tests: Make Karma browser timeout larger than the QUnit one

---

src/attributes/attr.js
test/data/mock.php
test/data/trusted-types-attributes.html
test/data/trusted-types-attributes.js
test/middleware-mockserver.js
test/unit/attributes.js

Stringifying attributes in the setter was needed for IE <=9 but it breaks
trusted types enforcement when setting a script `src` attribute.
Note that this doesn't mean script execution works. Since jQuery disables all
scripts by changing their type and then executes them by creating fresh script
tags with proper `src` & possibly other attributes, this unwraps any trusted
`src` wrappers, making the script not execute under strict CSP settings.
We might try to fix it in the future in a separate change.
Fixes gh-4948

Attributes: Don't stringify attributes in the setter

---

test/unit/css.js

Safari 9.1 & iOS 9.3 support CSS custom properties but that support
is buggy which crashes our tests. Disable those tests there.
See https://caniuse.com/css-variables

Tests: Disable CSS Custom Properties tests in old Safari/iOS

---

CONTRIBUTING.md

It used to say https://code.jquery.com/jquery.js but that's a frozen URL
to jQuery 1.11.1. Let's switch that to the URL to the Git build, i.e.
https://releases.jquery.com/git/jquery-git.js.

Docs: Update the URL to the latest jQuery build in CONTRIBUTING.md

---

.github/workflows/node.js.yml
Gruntfile.js

Migrate CI to Github Action.
- Add `node.js.yaml` to support github action.
- Modify `Gruntfile.js` to support running travis and github actions at the same time.

Build: Migrate CI to GitHub Actions

---

test/unit/ajax.js

In HTTP/2, status message is not supported and whatever is reported as
statusText differs between browsers. In Chrome & Safari it's "success", in
Firefox & IE it's "OK". So far "success" wasn't allowed. This made the tests
pass locally if you're running an HTTP/1.1 server but on TestSwarm which is
now proxied via an HTTP/2-equipped Cloudflare, the relevant test started failing
in Chrome & Safari.
Allow "success" to resolve the issue.

Tests: Allow statusText to be "success" in AJAX tests

---

test/unit/ajax.js

TestSwarm is now proxied via Cloudflare which cuts out headers relevant for
ETag tests, failing them. We're still running those tests in Karma on Chrome
& Firefox (including Firefox ESR).

Tests: Skip ETag AJAX tests on TestSwarm

---

src/css/curCSS.js

CSS does not acknowledge carriage return or form feed characters as whitespace but it does replace them _with_ whitespace, making it acceptable to use `rtrim`.

CSS: Justify use of rtrim on CSS property values

---

src/attributes/prop.js
src/queue/delay.js

Neither of the removed links is crucial; one of them refers to a site that has
since started being malicious; while the Web Archive links remain safe, some
scanners warn about such links. Removing them is the safest thing to do.
Fixes gh-4981

Docs: Remove links to Web Archive from source

---

test/data/jquery-1.9.1.js

Ref gh-4981
Ref gh-4991
We had removed the web archive links, but these links are still in the repo. Technically, the test folder is not distributed to releases, but we may as well remove them anyway.

Docs: remove expired links from old jquery source

---

test/unit/ajax.js
test/unit/core.js
test/unit/css.js
test/unit/data.js
test/unit/effects.js
test/unit/manipulation.js
test/unit/selector.js

PR gh-4993 changed a few too many issue references to `trac-NUMBER` ones. This
change fixes them. It also fixes a typo in one Trac issue number in selector
tests.
Ref gh-4993
For this, I manually went through all `trac-NUMBER` references for numbers below 5000 (I used regex `/trac-(?:\d{1,3}|[1-4]\d{3})\b/`).

Docs: Fix incorrect `trac-NUMBER` references

---

src/selector/uniqueSort.js
src/var/splice.js
test/unit/selector.js

Without this fix it does that
TypeError: results.splice is not a function
at Function.jQuery.uniqueSort (https://code.jquery.com/jquery-git.js:664:12)
at jQuery.fn.init.find (https://code.jquery.com/jquery-git.js:2394:27)
at gocusihafe.js:3:4
Reproduced here:
https://jsbin.com/gocusihafe/1/edit?html,css,js,console,output

Core: Don't rely on splice being present on input

---

src/attributes/classes.js
test/unit/attributes.js

This change makes jQuery skip falsy values in `addClass( array )`
& `removeClass( array )` instead of stopping iteration when the first falsy
value is detected. This makes code like:
```js
elem.addClass( [ "a", "", "b" ] );
```
add both the `a` & `b` classes.
The code was also optimized for size a bit.
Fixes gh-4998
+0 bytes thanks to the optimizations 🎉; initially it was at +8 bytes. In `toggleClass` we now also avoid needlessly recomputing the array of classes.
I'm yet to check how much can these optimizations be backported to 3.x-stable as we have some deprecated `toggleClass` logic there but I'll check after this lands.

CSS: Skip falsy values in `addClass( array )`, compress code

---

test/unit/core.js

Newer Firefox may report the column number smaller by 2 than it should.
Accept both values until the issue is fixed.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1751796

Tests: Workaround an XML parsing bug in Firefox

---

src/effects.js
test/unit/animation.js
test/unit/effects.js
test/unit/tween.js

`jQuery.fx.interval` has been deprecated since jQuery 3.0.0 but it has been
still used in jQuery code until this change.
The PR is divided into two commits. The first one just updates tests to parametrize them by a local `fxInterval` variable that's supposed to imitate `jQuery.fx.interval`. The second commit updates the source to remove `jQuery.fx.interval` and changes the value of `fxInterval` in tests from 10 to 13 as it's no longer possible to tweak this value which has been done until now.
Each of the commits passes tests.
-12 bytes 🎉

Effects: Remove jQuery.fx.interval

---

build/tasks/build.js
build/tasks/lib/slim-build-flags.js
test/.eslintrc.json
test/data/testinit-jsdom.js
test/data/testinit.js
test/unit/ajax.js
test/unit/animation.js
test/unit/attributes.js
test/unit/basic.js
test/unit/callbacks.js
test/unit/core.js
test/unit/css.js
test/unit/deferred.js
test/unit/deprecated.js
test/unit/dimensions.js
test/unit/effects.js
test/unit/manipulation.js
test/unit/offset.js
test/unit/queue.js
test/unit/ready.js
test/unit/serialize.js
test/unit/support.js
test/unit/tween.js
test/unit/wrap.js

Introduces a new test API, `includesModule`. The method returns whether
a particular module like "ajax" or "deprecated" is included in the current
jQuery build; it handles the slim build as well. The util was created so that
we don't treat presence of particular APIs to decide whether to run a test as
then if we accidentally remove an API, the tests would still not fail.

Tests: Exclude tests based on compilation flags, not API presence

---

build/tasks/build.js
build/tasks/lib/slim-build-flags.js
test/.eslintrc.json
test/data/testinit-jsdom.js
test/data/testinit.js
test/unit/ajax.js
test/unit/animation.js
test/unit/attributes.js
test/unit/basic.js
test/unit/callbacks.js
test/unit/core.js
test/unit/css.js
test/unit/deferred.js
test/unit/deprecated.js
test/unit/dimensions.js
test/unit/effects.js
test/unit/manipulation.js
test/unit/offset.js
test/unit/queue.js
test/unit/ready.js
test/unit/serialize.js
test/unit/support.js
test/unit/tween.js
test/unit/wrap.js

`3.x-stable` version of #5046.
Introduces a new test API, `includesModule`. The method returns whether
a particular module like "ajax" or "deprecated" is included in the current
jQuery build; it handles the slim build as well. The util was created so that
we don't treat presence of particular APIs to decide whether to run a test as
then if we accidentally remove an API, the tests would still not fail.

Tests: Exclude tests based on compilation flags, not API presence (3.x version)

---

build/fixtures/README.md

webpack has migrated to https://webpack.js.org/ since version 2.

Docs: Update webpack website in README

---

.github/workflows/codeql-analysis.yml

All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/
Fixes gh-5039

chore: remove git.io

---

test/karma.debug.html

Without this fix, the layout is fine during the test run but all the CSS is gone
when tests finish and the results are shown.
This affects commands like `grunt karma:chrome-debug`.

Tests: Fix the link to QUnit CSS file

---

src/core/init.js

The third parameter of `jQuery.fn.init` - `root` - was just needed to support
`jQuery.sub`. Since this API has been removed in jQuery 1.9.0 and Migrate 3.x
is not filling it in, this parameter is no longer needed.
This parameter has never been documented but it's safer to remove it in a major
update.
It would still be good to put that in the upgrade guide.
-2 bytes

Core: Drop the root parameter of jQuery.fn.init

---

src/css/curCSS.js
test/unit/css.js

CSS: Don’t trim whitespace of undefined custom property

---

test/unit/core.js

Firefox 96-100 used to report the column number smaller by 2 than it should
in the `parsererror` element generated for invalid XML documents. Since that
version range is unsupported now and it includes no ESR versions, the workaround
can now be dropped.
Ref gh-5018

Tests: Remove a workaround for a Firefox XML parsing issue

---

src/manipulation.js
src/manipulation/domManip.js
test/unit/ajax.js

We've already had `buildFragment` extracted to a separate file long ago. `domManip` is quite a complex & crucial API and so far it has existed within the `manipulation.js` module. Extracting it makes the module shorter and easier to understand.
A few comments / messages in tests have also been updated to not suggest there's a public `jQuery.domManip` API - it's been private since 3.0.0.

Manipulation: Extract domManip to a separate file

---

src/selector.js
test/unit/selector.js

This backports custom pseudos tests from Sizzle; they were missed in original test backports. Also, the support for legacy custom pseudos has been dropped.

Selector: Drop support for legacy pseudos, test custom pseudos

---

src/ajax.js
src/ajax/xhr.js
test/data/mock.php
test/unit/ajax.js

According to the docs, one can use `null` as a success function in `jQuery.get`
of `jQuery.post` so the following:
```js
await jQuery.get( "https://httpbin.org/json", null, "text" )
```
should get the text result. However, this shortcut hasn't been working so far.
Fixes gh-4989

Ajax: Support `null` as success functions in `jQuery.get`

---

README.md

This removes the stale badge on the README from Fossa. It may be a temporary loss of service, but I'd prefer not to have badges that don't load.

Docs: remove stale badge

---

src/selector/contains.js
test/unit/manipulation.js
test/unit/selector.js

The `<template/>` element `contents` property is a document fragment that may
have a `null` `documentElement`. In Safari 16 this happens in more cases due
to recent spec changes - in particular, even if that document fragment is
explicitly adopted into an outer document. We're testing both of those cases
now.
The crash used to happen in `jQuery.contains`. As it turns out, we don't need
to query the supposed container `documentElement` if it has the
`Node.DOCUMENT_NODE` (9) `nodeType`; we can call `.contains()` directly on
the `document`. That avoids the crash.
Fixes gh-5147
-18 bytes

Selector:Manipulation: Fix DOM manip within template contents

---

src/selector/support.js
test/unit/support.js

Firefox 106 adjusted to the spec mandating that `CSS.supports("selector(...)")` uses non-forgiving parsing which makes it pass the relevant support test.
Note: I only check for Fx 102 in the test as it's just a support test and Fx 102 is an ESR version; the other tested ones will soon go out of support. This means the test will only start passing tomorrow once Firefox 106 gets released.

Tests: Indicate Firefox 106+ passes the `cssSupportsSelector` test

---

src/selector/uniqueSort.js
test/unit/selector.js

Some APIs, like `.prevAll()`, return elements in the reversed order, causing confusing behavior when used with wrapping methods (see gh-5149 for more info)
To provide an easy workaround, this commit implements a chainable `uniqueSort`
method on jQuery objects, an equivalent of `jQuery.uniqueSort`.
Fixes gh-5166
+12 bytes

Selector: Implement the `uniqueSort` chainable method

---

.github/workflows/codeql-analysis.yml
.github/workflows/node.js.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

Build: Limit permissions for GitHub workflows

---

src/selector.js
src/selector/rbuggyQSA.js
src/selector/support.js
test/unit/selector.js

jQuery 3.6.2 started using `CSS.supports( "selector(SELECTOR)" )` before using `querySelectorAll` on the selector. This was to solve gh-5098 - some selectors, like `:has()`, now have their parameters parsed in a forgiving way, meaning that `:has(:fakepseudo)` no longer throws but just returns 0 results, breaking that jQuery mechanism.
A recent spec change]() made `CSS.supports( "selector(SELECTOR)" )` always use non-forgiving parsing, allowing us to use this API for what we've used `try-catch` before.
To solve the issue on the spec side for older jQuery versions, `:has()` parameters are no longer using forgiving parsing in the latest spec update but our new mechanism is more future-proof anyway.
However, the jQuery implementation has a bug - in
`CSS.supports( "selector(SELECTOR)" )`, …

Selector: Make selector lists work with `qSA` again

---

build/tasks/build.js
package.json

When trying to run a test release, I learned that the Insight package is no longer maintained and no longer works on a fresh install. This PR removes it from the 3.6-stable branch.

Build: remove stale Insight package from custom builds

---

test/.eslintrc.json
test/middleware-mockserver.js

The `test/middleware-mockserver.js` file used to have the same ESLint settings applied as other test files that are directly run in tested browsers. Now it shares settings of other Node.js files.
The file is now also written using modern JS, leveraging ES2018.

Build: Migrate middleware-mockserver to modern JS

---

src/ajax/script.js
test/unit/ajax.js

The AJAX script transport has two versions: XHR + `jQuery.globalEval` or appending a script tag (note that `jQuery.globalEval` also appends a script tag now, but inline). The former cannot support the `headers` option which has so far not been taken into account.
For jQuery 3.x, the main consequence was the option not being respected for cross-domain requests. Since in 4.x we use the latter way more often, the option was being ignored in more cases.
The transport now checks whether the `headers` option is specified and uses the XHR way unless `scriptAttrs` are specified as well.
Fixes gh-5142
+5 bytes

Ajax: Support `headers` for script transport even when cross-domain

---

src/deferred/exceptionHook.js
test/unit/deferred.js

So far, `jQuery.Deferred.exceptionHook` used to log error message and stack separately. However, that breaks browser applying source maps against the stack trace - most browsers require logging an error instance. This change makes us do exactly that.
One drawback of the change is that in IE 11 previously stack was printed directly and now just the error summary; to get to the actual stack trace, three clicks are required. This seems to be a low price to pay for having source maps work in all the other browsers, though.
Safari with the new change requires one click to get to the stack trace which sounds manageable.
Fixes gh-3179
Ref https://crbug.com/622227
`-12 bytes`
I'd like to keep it a 4.x item only, for two reasons:
* this may be an edge case but some integrations may depend on our …

Deferred: Respect source maps in jQuery.Deferred.exceptionHook

---

package.json
src/ajax.js
src/ajax/binary.js
src/jquery.js
test/data/mock.php
test/data/testinit.js
test/middleware-mockserver.js
test/unit/ajax.js

~~**NOTE:** Please don't review the first commit; that one is #5196, it was just easier for me to depend on it.~~ (that PR landed)
Two changes have been applied:
* prefilters are now applied before data is converted to a string;
this allows prefilters to disable such a conversion
* a prefilter for binary data is added; it disables data conversion
for non-string non-plain-object `data`; for `FormData` bodies, it
removes manually-set `Content-Type` header - this is required
as browsers need to append their own boundary to the header
Ref gh-4150
`+39 bytes`. We should discuss whether we want this fully in core or just the small change of running prefilters early enough for this to be possible. It is quite generic, though, with the small exception of special `FormData` treatment - which, I …

Ajax: Support binary data (including FormData)

---

package.json
src/selector.js
src/selector/rbuggyQSA.js
src/selector/support.js
test/unit/support.js

`CSS.supports( "selector(...)" )` has different semantics than selectors passed to `querySelectorAll`. Apart from the fact that the former returns `false` for unrecognized selectors and the latter throws, `qSA` is more forgiving and accepts some invalid selectors, auto-correcting them where needed - for example, mismatched brackers are auto-closed. This behavior difference is breaking for many users.
To add to that, a recent CSSWG resolution made `:is()` & `:where()` the only pseudos with forgiving parsing; browsers are in the process of making `:has()` parsing unforgiving.
Taking all that into account, we go back to our previous try-catch approach without relying on `CSS.supports( "selector(...)" )`. The only difference is we detect forgiving parsing in `:has()` and mark the selector as …

Selector: Stop relying on CSS.supports( "selector(...)" )

---

build/release/cdn.js

I wanted to see if the release could be run on Windows. To my surprise, the md5 hash was the only thing that didn't work.
This checks the OS and switches up the command used for the md5 sums and formats it the same way as default mac/linux.

Release: add support for md5 sums in windows

---

src/deferred.js
src/deferred/exceptionHook.js
test/unit/deferred.js

Rename `jQuery.Deferred.getStackHook` to `jQuery.Deferred.getErrorHook` to indicate passing an error instance is usually a better choice - it works with source maps while a raw stack generally does not.
In jQuery `3.7.0`, we'll keep both names, marking the old one as deprecated. In jQuery `4.0.0` we'll just keep the new one. This change implements the `4.0.0` version; PR gh-5212 implements the `3.7.0` one.
Fixes gh-5201
Ref gh-5212

Deferred: Rename `getStackHook` to `getErrorHook`

---

src/deferred.js
src/deferred/exceptionHook.js
test/unit/deferred.js
test/unit/deprecated.js

Rename `jQuery.Deferred.getStackHook` to `jQuery.Deferred.getErrorHook` to indicate passing an error instance is usually a better choice - it works with source maps while a raw stack generally does not.
In jQuery `3.7.0`, we'll keep both names, marking the old one as deprecated. In jQuery `4.0.0` we'll just keep the new one. This change implements the `3.7.0` version; PR gh-5211 implements the `4.0.0` one.
Fixes gh-5201
Ref gh-5211

Deferred: Rename `getStackHook` to `getErrorHook` (3.x version)

---

test/unit/deprecated.js

PR gh-5046 erroneously changed AJAX deprecated event alias usage in deprecated tests to `.on()` calls. This change reverses this mistake.

Tests: Test AJAX deprecated event aliases properly

---

src/ajax/binary.js
test/unit/ajax.js

The way gh-5197 implemented binary data handling, `processData` was being explicitly set to `false`. This is expected but it made it impossible to override it to `true`. The new logic will only set `processData` to `false` if it wasn't explicitly passed in original options.
Ref gh-5197

Ajax: Allow `processData: true` even for binary data

---

src/ajax/binary.js
test/unit/ajax.js

PR gh-5197 started treating all non-string non-plain-object `data` values as binary. However, `jQuery.ajax` also supports arrays as values of `data`. This change makes regular arrays no longer be considered binary data.
Surprisingly, we had no tests for array `data` values; otherwise, we'd detect the issue earlier. This change also adds a few such missing tests.
Ref gh-5197

Ajax: Don't treat array data as binary

---

src/event.js
test/unit/event.js

In IE (all versions), `focus` & `blur` handlers are fired asynchronously
but `focusin` & `focusout` are run synchronously. In other browsers, all
those handlers are fired synchronously.
Simulate `focus` via `focusin` & `blur` via `focusout` in IE to
avoid these issues.
Fixes gh-4856
Fixes gh-4859
Fixes gh-4950
+30 bytes

Event: Simulate focus/blur in IE via focusin/focusout

---

src/event.js
test/unit/event.js

In `leverageNative`, instead of calling `event.stopImmediatePropagation()` which would abort both native & jQuery handlers, set the wrapper's `isImmediatePropagationStopped` property to a function returning `true`. Since for each element + type pair jQuery attaches only one native handler, there is also only one wrapper jQuery event so this achieves the goal: on the target element jQuery handlers don't fire but native ones do.
Unfortunately, this workaround doesn't work for handlers on ancestors - since the native event is re-wrapped by a jQuery one on each level of the propagation, the only way to stop it for jQuery was to stop it for everyone via native `stopPropagation()`. This is not a problem for `focus`/`blur` which don't bubble, but it does also stop `click` on checkboxes and …

Event: Make trigger(focus/blur/click) work with native handlers

---

src/selector.js

In IE 9 accessing `document.activeElement` may throw; see https://bugs.jquery.com/ticket/13393. We've already guarded against this in `event` code but not in `selector`.
Due to gzip magic, this is +0 bytes.

Selector: Wrap activeElement access in try-catch

---

src/event.js

Previously, when `leverageNative` handled async events, there was a case where an empty placeholder object was set as a result. Covering both such an object and `false` required a `length` check. However, this is not necessary since gh-5223 and the check was already simplified in other places; this one was missed.
Ref gh-5223
-1 byte

Event: Simplify the check for saved data in leverageNative

---

src/event.js
test/unit/event.js

This is a follow-up to similar changes to data & event storages from gh-4603.
This is a breaking change as there may be code like:
```js
jQuery.event.special.hasOwnProperty( "something" )
```
in the wild.
Ref gh-4603
+3 bytes

Event: Avoid collisions between jQuery.event.special & Object.prototype

---

src/css.js
test/unit/dimensions.js

This regressed in gh-3656 as the added logic to include scroll gutters in `.innerWidth()` / `.innerHeight()` didn't take negative margins into account. This broke handling of negative margins in `.offsetHeight( true )` and `.offsetWidth( true )`. To fix it, calculate margin delta separately and only add it after the scroll gutter adjustment logic.
Fixes gh-3982
Ref gh-3656
+4 bytes

CSS: Make `offsetHeight( true )`, etc. include negative margins

---

src/selector/support.js
test/unit/support.js

Chrome 112 & Safari 16.4 introduce two changes:
* `:has()` is non-forgiving
* `CSS.supports( "selector(...)" )` parses everything in a non-forgiving way
We no longer care about the latter but the former means the `cssHas` support test now passes.
`3.x-stable` version: #5226

Tests: Indicate Chrome 112 & Safari 16.4 pass the cssHas support test

---

src/selector.js
test/unit/support.js

Chrome 112 & Safari 16.4 introduce two changes:
* `:has()` is non-forgiving
* `CSS.supports( "selector(...)" )` parses everything in a non-forgiving way
We no longer care about the latter but the former means the `cssHas` support test now passes.
`main` version: #5225

Tests: Indicate Chrome 112 & Safari 16.4 pass the cssHas support test (3.x version)

---

src/deprecated/event.js

Make the deprecated `.hover()` method not rely on other deprecated methods: `.mouseenter()` & `.mouseleave()`. Use `.on()` instead.

Deprecated: Define `.hover()` using non-deprecated methods

---

Gruntfile.js

There was a mistake in paths logic that made the `dist/` folder linted even in the `eslint:dev` task which is run before the build. Fix that by explicitly ignoring the `dist/` folder at the end of the file list.

Build: Make the `eslint:dev` task not lint the `dist/` folder

---

.github/PULL_REQUEST_TEMPLATE.md

Now that unit tests are run on GitHub Actions in all three major engines and for multiple custom jQuery builds, the request for PR authors to run unit tests locally and confirm they pass is needless overhead; let's drop the checkbox.

Docs: Remove the "Grunt build" section from the PR template

---

Gruntfile.js
build/tasks/build.js
build/tasks/sourcemap.js
package.json

UglifyJS is ES5-only, while Terser supports newer ECMAScript versions. jQuery is authored in ES5 but jQuery 4.x will also have an ESM build that cannot be minified using UglifyJS directly.
We could strip the `export` statement, minify via UglifyJS and re-add one but that increases complexity & may not fully play nice with source maps.
On the other hand, switching to Terser increases the minfied size by just 324 bytes and the minified gzipped one by just 70 bytes. Such differences largely disappear among bigger size gains from the `3.x-stable` line - around 2.7 KB minified gzipped as of now.

Build: Switch the minifier from UglifyJS to Terser

---

src/selector-native.js
src/selector.js
test/unit/selector.js

`Sizzle.tokenize` is an internal Sizzle API, but exposed. As a result,
it has historically been available in jQuery via `jQuery.find.tokenize`.
That got dropped during Sizzle removal; this change restores the API.
Some other APIs so far only exposed on the `3.x` line are also added
back:
* `jQuery.find.select`
* `jQuery.find.compile`
* `jQuery.find.setDocument`
In addition to that, Sizzle tests have been backported for the following
APIs:
* `jQuery.find.matchesSelector`
* `jQuery.find.matches`
* `jQuery.find.compile`
* `jQuery.find.select`
A new test was also added for `jQuery.find.tokenize` - even Sizzle was
missing one.
Fixes gh-5259
Ref gh-5260
Ref jquery/sizzle#242
Ref gh-5113
Ref gh-4395
Ref gh-4406
`3.x-stable` version of this PR: #5260
+34 bytes

Selector: Re-expose jQuery.find.{tokenize,select,compile,setDocument}

---

src/selector.js
test/unit/selector.js

`Sizzle.tokenize` is an internal Sizzle API, but exposed. As a result, it has historically been available in jQuery via `jQuery.find.tokenize`. That got dropped during Sizzle removal; this change restores the API.
In addition to that, Sizzle tests have been backported for the following APIs:
* `jQuery.find.matchesSelector`
* `jQuery.find.matches`
* `jQuery.find.compile`
* `jQuery.find.select`
A new test was also added for `jQuery.find.tokenize` - even Sizzle was missing one.
Fixes gh-5259
Ref jquery/sizzle#242
Ref gh-5113
Ref gh-4395
Ref gh-4406
`main` version of this PR: #5263
+8 bytes

Selector: Re-expose jQuery.find.tokenize (3.x version)

---

src/core.js
test/unit/manipulation.js

Fixes https://github.com/jquery/jquery/issues/5264.
Size comparison, if written as minimal diff (add conditional branch):
```                              
+54     +8 dist/jquery.js                                                   
+19     +5 dist/jquery.min.js   
```
Size comparison, as submitted (rewritten without "else if"):
```
raw     gz Compared to 3.x-stable @ 992a66538b535d24c9ba46c3a4492665943b40c7
+50     +4 dist/jquery.js                                                   
+4     +1 dist/jquery.min.js  
```

Core: Fix regression in jQuery.text() on HTMLDocument objects

---

.github/workflows/codeql-analysis.yml
.github/workflows/node.js.yml

Resolves https://github.com/jquery/jquery/issues/5266
It's important to make sure the SHA's are from the original repositories and not forks. I have manually verified all of them and added references in the commit descriptions.

Build: Reference GitHub Actions by commit SHAs

---

README.md

This removes the gitter badge and adds a link to the current meeting place and meeting minutes.

Docs: remove stale gitter badge from readme

---

test/unit/selector.js

Firefox 114+ no longer match on backslashes in `:lang()`, even when escaped. It is an intentional change as `:lang()` parameters are supposed to be valid BCP 47 strings. Therefore, we won't attempt to patch it. We'll keep this test here until other browsers match the behavior.
Fixes gh-5271
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1839747#c1 Ref https://github.com/w3c/csswg-drafts/issues/8720#issuecomment-1509242961

Tests: Disable the ":lang respects escaped backslashes" test

---

.gitattributes

We've had this rule for `*.js` files so far but we now have two new JS extensions.
Another option is to set this for all text files, not just JS. Is there any downside? AFAIK most Windows editors/IDEs should handle LF line endings just fine nowadays?

Build: Make sure `*.cjs` & `*.mjs` files use UNIX line endings as well

---

Gruntfile.js
build/tasks/build.js
build/tasks/minify.js
build/tasks/sourcemap.js
package.json

Also, as part of this, fix the `file` & `sources` properties of the source map file.
Fixes gh-5285
Ref gh-5258
-18 bytes

Build: Switch form Terser to SWC for JS minification

---

src/selector.js

Both IE & Edge Legacy need the workaround of calling `setDocument()` in an `unload` handler to avoid "permission denied" errors. However, due to not being possible to feature-detect this issue, the handler has been applied in all browsers for windows different than the one in which jQuery was loaded.
jQuery 4.0, which drops Edge Legacy support, guards this workaround with a `document.documentMode` check. This won't work in the 3.x line due to still supporting Edge Legacy but we can check for
`document.documentElement.msMatchesSelector` instead as that API is supported in IE 9+ and all Edge Legacy versions.
Fixes gh-5281
Ref gh-4792
+6 bytes

Selector: Only attach the unload handler in IE & Edge Legacy

---

Gruntfile.js
package.json
src/css/support.js
test/data/support/bootstrap.html
test/unit/support.js

Bootstrap 5 includes the following CSS on the page:
```css
*,
*::before,
*::after {
box-sizing: border-box;
}
```
That threw our `reliableTrDimensions` support test off. This change fixes the support test and adds a unit test ensuring support test values on a page including Bootstrap 5 CSS are the same as on a page without it.
Fixes gh-5270
+10 bytes
3.x version: #5279

CSS: Make the reliableTrDimensions support test work with Bootstrap CSS

---

build/tasks/minify.js

SWC is not respecting the git setting and does not have an option to force LF. This fixes the build on Windows.

Build: replace CRLF with LF during minify

---

build/fixtures/README.md

Also, fix an example importing from `jquery/src/css.js` as that is supposed to use named exports now.

Core: Add more info about named exports

---

src/css/curCSS.js
src/selector.js
src/selector/rbuggyQSA.js
src/selector/selectorError.js
src/selector/tokenize.js
src/var/rtrimCSS.js
test/unit/core.js
test/unit/selector.js

Bring some changes from `3.x-stable`:
* rename `rtrim` to `rtrimCSS` to distinguish from the previous `rtrim` regex used for `jQuery.trim`
* backport one `id` selector test that avoids the selector engine path
* remove the inner function wrapper from `selector.js` by renaming the imported `document.js` value
The changes also improve the size a little.

CSS:Selector: Align with 3.x, remove the outer `selector.js` wrapper

---

build/tasks/compare_size.mjs

Sorts the branches and keep "last run" last.

Build: sort branches in compare_size; last run last

---

build/fixtures/README.md

The package README used to show examples importing from a regular jQuery file; this won't work natively. Instead, use module versions of jQuery in these examples.

Docs: Fix module links in the package README

---

src/css/support.js
test/data/css/cssComputeStyleTests.html
test/data/testinit.js
test/unit/css.js

If the iframe is not initially visible, `boxSizingReliableVal` gets set to false, which triggers this code to set the wrong dialog width here: https://github.com/jquery/jquery/blob/a7cc3a0f0418d168ff3818576161c5af24d0ca78/src/css.js#L418-L426
I think this should solve https://github.com/jquery/jquery-ui/issues/2176.
You can reproduce something similar to the original issue by creating the following two files in the top level of a website. Then go to `index.html`, click "Show Frame", then "Show Popup". The popup should be 600px, but is not.
```html
<!DOCTYPE html>
<html>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js" integrity="sha512-+k1pnlgt4F1H8L7t3z95o3/KO+o78INEcXTbnoJQ/F2VqDVhWoaiVml/OEHv9HsVgxUaVW+IbiZPUJQfF/YxZw==" crossorigin="anonymous" …
```

CSS: Fix support test results for initially hidden iframes

---

src/css/support.js
test/data/css/cssComputeStyleTests.html
test/data/testinit.js
test/unit/css.js

Followup to gh-5317 - that PR didn't apply to the reliableTrDimensions support test.
`3.x-stable` version of this PR: #5359

CSS: Fix reliableTrDimensions support test for initially hidden iframes

---

src/css.js
src/css/support.js
test/data/css/cssComputeStyleTests.html
test/unit/css.js

Followup to gh-5317 - that PR didn't apply to the reliableTrDimensions support test.
Also, account for the fact old Firefox (<61) has `null` computed style for elements in such iframes.
`main` version of this PR: #5358

CSS: Fix reliableTrDimensions test for initially hidden iframes (3.x)

---

test/unit/css.js

Old iOS (<10) always rounds widths down, account for this in tests.

Tests: Workaround a tr width test issue in old iOS

---

.github/workflows/codeql-analysis.yml
.github/workflows/node.js.yml

Without this change, dependabot PRs run double checks - one set for the `push` part and one for the `pull_request` part.
I tested it on my fork.
PR against `jquery/jquery` (i.e. without this fix):
PR against `mgol/jquery` with this fix applied:

Build: Don't run CI push workflows for dependabot branches

---

.github/workflows/codeql-analysis.yml
.github/workflows/node.js.yml
package-lock.json

Batching a few dependabot PRs to avoid landing 5 different commits.
1: Bump actions/cache from 3.3.1 to 3.3.2
Bumps [actions/cache](https://github.com/actions/cache) from 3.3.1 to 3.3.2.
- [Release notes](https://github.com/actions/cache/releases)
- [Changelog](https://github.com/actions/cache/blob/main/RELEASES.md)
- [Commits](https://github.com/actions/cache/compare/88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8...704facf57e6136b1bc63b828d79edcd491f0ee84)
---
updated-dependencies:
- dependency-name: actions/cache dependency-type: direct:production update-type: version-update:semver-patch ...
2: Bump actions/checkout from 3.6.0 to 4.1.1
Bumps [actions/checkout](https://github.com/actions/checkout) from 3.6.0 to 4.1.1.
- [Release notes](https://github.com/actions/checkout/releases)
- …

Build: Bump @babel/traverse & multiple actions

---

.github/workflows/codeql-analysis.yml
.github/workflows/node.js.yml

Use Prettier 3.1.0 to reformat the Yaml files. This makes their format identical to the one used on `3.x-stable`, making for much easier cherry-picks.
The main difference is the list under `steps:` was not indented while all other lists were.
Running the same version of Prettier on `3.x-stable` Yaml files results in no changes.

Build: Reformat GitHub workflow Yaml files

---

src/attributes/attr.js
src/attributes/prop.js
src/css.js
src/manipulation.js
src/offset.js

There are two main reasons for why some of those dependencies are no longer needed:
1. `jQuery.contains` which is now a part of `core`.
2. `jQuery.find.attr` no longer exists, native `getAttribute` is used instead.

Selector: Eliminate `selector.js` depenencies from various modules

---

src/core/DOMEval.js
test/unit/manipulation.js

Fixes gh-5377
Don't try to remove a script element that has already removed itself.
With nearby improvements, +12 bytes to jquery.min.js (+1 gzipped).

Manipulation: Support $el.html(selfRemovingScript)

---

src/attributes/attr.js
src/selector-native.js
src/selector.js
src/selector/var/booleans.js

This fixes custom builds using the `--include` switch that don't include the `attributes` module.
Fixes gh-5379

Selector: Make `selector.js` module depend on `attributes/attr.js`

---

test/unit/manipulation.js

Ref gh-5378
Work around the lack of `document.currentScript` with explicit IDs.

Manipulation: Generalize a test to support IE

---

src/attributes/attr.js

The `attrHooks` entries for boolean attributes are only defined for jQuery 4+; jQuery 3.x used a separate mechanism - assigning them to `jQuery.expr.attrHandle`. That object used to be maintained by Sizzle, since jQuery 3.7.0 it's kept in the selector module. Because of that, the `isXMLDoc` check used to be require in this hook.
Now that standard `attrHooks` are used, the `isXMLDoc` check already happens inside of `jQuery.attr` and there's no need to repeat it in the test. Note that this repetition is even incorrect - while Sizzle's `jQuery.find.attr` used to treat an `undefined` output of the hooks from `jQuery.expr.attrHandle` as a way to opt out of the hook, jQuery's `attrHooks` use `null` to opt out of a getter hook.
Apart from the size, this patch also avoids unnecessary extra …

Attributes: Shave off a couple of bytes

---

build/release.js

The build command needed to be updated to `npm run build:all`. It used to be `npx grunt`.

Release: update build command in Release.generateArtifacts

---

build/release/dist.js

- this became necessary due to the addition of the prepare script
- scripts aren't needed and don't work in the dist repo
Hit this snag on the last step testing npm publish in the dist repo, which tried to run the new `prepare` script, which of course failed.

Release: remove scripts and dev deps from dist package.json

---

build/release.js
build/release/dist.js
build/tasks/build.js
build/tasks/compare_size.mjs

- also add the ability to pass VERSION in env to test final builds
- adjust sha regex to account for lack of shas
- set the version on the dist package.json

Release: use buildDefaultFiles directly and pass version

---

test/middleware-mockserver.cjs

Node.js 20 started throwing errors when `writeHead` is called twice on a response. This might have already been invalid before but it wasn't throwing on Node.js 18.
Compute the headers object and call `writeHead` once to avoid the issue.

Tests: Fix Karma tests on Node.js 20

---

test/middleware-mockserver.js

Remove a redundant Express-targeted `resp.set` call from the `script` handler in `middleware-mockserver.js` as was done on the `main` branch.
Ref gh-5397

Tests: Align `middleware-mockerver.js` with the `main` branch

---

test/runner/browserstack/browsers.js
test/runner/browserstack/queue.js
test/runner/run.js

Add some minor improvements after watching the recent first run on 3.x-stable, including:
- fix the flakey message for when a test fails and then passes on retry.
- ignore worker delete failures. We hit this in one browser. The tests all passed and the worker had stopped, but BrowserStack returned a 502.

Tests: fix flakey message logs; ignore delete worker failures

---

.github/workflows/filestash.yml

3.x companion of https://github.com/jquery/jquery/pull/5434
Replaces the jenkins workflow to update git versions of jQuery on the Filestash server. The filestash environment is already set up in the jQuery repo settings and includes the necessary SSH private key and filestash server URL.
Here's a sample of the 3.x workflow running as a dry run: 
https://github.com/timmywil/jquery/actions/runs/8205774067/job/22443405621
We should disable the jenkins workflow before merging.

Build: add GitHub Actions workflow to update Filestash

---

.github/workflows/browserstack.yml
test/runner/browserstack/browsers.js
test/runner/browserstack/queue.js
test/runner/command.js
test/runner/createTestServer.js
test/runner/run.js

3.x version of #5438 
Add the ability to retry by restarting the worker and getting a different browser instance, after all normal retries have been exhausted. This can sometimes be successful for flakey tests when a refresh is not.

Tests: add --hard-retries option to test runner

---

test/runner/reporter.js

Add the actual and expected messages to the reporter.
Also, I realized that `test.errors` contained all the failed assertions and `test.assertions` contained only passed ones, so I was able to clean up that code a bit.

Tests: add actual and expected messages to test reporter

---

test/runner/reporter.js

3.x version of #5448 
- Show actual and expected values even if they are falsey.
- Also leave out message if none was provided, rather than printing `undefined`.

Tests: show any and all actual/expected values

---

src/attributes/attr.js
test/unit/attributes.js
test/unit/selector.js

The HTML spec defines boolean attributes:
https://html.spec.whatwg.org/#boolean-attributes
that often correlate with boolean properties. If the attribute is missing, it correlates with the `false` property value, if it's present - the `true` property value. The only valid values are an empty string or the attribute name.
jQuery tried to be helpful here and treated boolean attributes in a special way in the `.attr()` API:
1. For the getter, as long as the attribute was present, it was returning the attribute name lowercased, ignoring the value.
2. For the setter, it was removing the attribute when `false` was passed; otherwise, it was ignoring the passed value and set the attribute - interestingly, in jQuery `>=3` not lowercased anymore.
The problem is the spec occasionally converts …

Attributes: Make `.attr( name, false )` remove for all non-ARIA attrs

---

test/runner/listeners.js
test/runner/reporter.js

Differences are:
- use `diffChars` when both expected and actual are strings
- use `diffWords` for everything after that
Objects, arrays, and numbers are diffed as before.

Tests: improve diffing for values of different types

---

src/offset.js
test/unit/offset.js

Continue searching for the next positioned offsetParent (or the document) when calculating `position()`.
This fixes the seemingly inconsistent behaviour that occurred when calling `position()` on elements inside tables; for which the [offsetParent](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent) changes based on its `position` css property. e.g
```
<div id="positioned-container" style="position: relative;">
<table>
<tr>
<td>
<span id="static"></span>
<span id="relative" style="position: relative;"></span>
<span id="absolute" style="position: absolute;"></span>
</td>
</tr>
</table>
</div>
The offsetParent of #static is td
The offsetParent of #relative and #absolute is #positioned-container
```
Previously `$('#static').position()` was returning the position …

Offset: Increase search depth when finding the 'real' offset parent

---

README.md
build/fixtures/README.md

Update a few remaining HTTP URLs to HTTPS. The only ones left are XMLNS-like URLs or ones to localhost - those need to stay as-is.

Docs: Update remaining HTTP URLs to HTTPS

---

.github/workflows/browserstack.yml

It's common for us to merge to main and cherry pick to 3.x-stable, so it's best if concurrency is shared between branches, which is effectively what we had already as it matches on workflow name and browser. Ideally, it could also match on the corresponding commit, but it seems the commit message is not available in the github context.

Tests: revert concurrency group change

---

test/unit/selector.js

Use `assert.selectInFixture` consistently in `:has` tests. Previously, any test failure that happened before this test run made it fail due to an additional paragraph with id `qunit-testresult` injected by QUnit.

Tests: Make `:has` selector tests not vulnerable to unrelated failures

---

test/unit/selector.js

Consistently use `assert.selectInFixture` instead of prepending the selector with `#qunit-fixture ` manually.
Ref gh-5497

Tests: Align `:has` selector tests with `3.x-stable`

---

src/css/support.js
test/data/support/zoom.html
test/unit/css.js
test/unit/support.js

Firefox 126+ implements CSS zoom in a way it affects width computed style
very slightly (`100.008px` instead of `100px`); accept that difference.
Add a test for support tests resolving the same under CSS zoom & without one.
That test uncovered Chrome failing the `reliableTrDimensions` support test
under zoom; the test has been fixed.
Fixes gh-5489
Closes gh-5495
Ref gh-5496
`3.x` version: gh-5496

CSS:Tests: Fix tests & support tests under CSS Zoom

---

test/unit/offset.js

- iOS 12 and below do not support scrollTop/Left on the
window or document. Before 82169df, window.supportsScroll
was always undefined. There were 2 issues: (1) iOS <=12 do
support scroll props on the body, so the support test
wasn't helpful. (2) one test checked the wrong window and
the value was always undefined, which meant those tests
never ran in any browser.
Sample BrowserStack run: https://github.com/timmywil/jquery/actions/runs/9449886713

Tests: fix supportsScroll feature test in offset

---

test/unit/offset.js

- some offset tests related to fixed positioning were not running in any browser. Rather than fixing the support test, I've removed it as it's no longer needed for the current browser list.
Sample BrowserStack run: https://github.com/timmywil/jquery/actions/runs/9449771847

Tests: remove unnecessary scroll feature test

---

.github/workflows/verify-release.yml
.release-it.cjs
build/release/verify.js
package-lock.json
package.json

I attempted the release this morning and noticed a couple things after the initial steps.
1. The version was not set in the built files. `VERSION` needed to be set in the environment. The `version` is not available in script contexts at the `init` stage. This adds a full build to `after:bump` with the new version, which happens just before publishing to npm. I added `cross-env` to do this so it works on Windows as well.
2. The last build to run in `npm test` was `selector-native`, so the main jquery.js file was not correct.
Also:
- order hooks in execution order
- upgrade actions in the new verify workflow
- verify.js did not need to export and could be run from the file

Release: ensure builds have the proper version

---

test/data/qunit-fixture.html
test/unit/attributes.js
test/unit/core.js
test/unit/deprecated.js
test/unit/effects.js
test/unit/manipulation.js
test/unit/selector.js
test/unit/traversing.js

Looks like we had already converted links to https, but they were still dead links (or were not what they used to be). This is the 4.x version of my [3.x commit](https://github.com/jquery/jquery/pull/5531/commits/250ad48e51b3d6a5b1bc71ad03424e8cb82c9cfc) to replace these links with ones that should last long into the future.

Tests: replace dead links in qunit fixture

---

.github/workflows/browserstack.yml
.github/workflows/node.js.yml

1. At the same time, there may be two supported versions of Firefox ESR. Run tests on both, installed locally.
2. Don't run tests on Firefox 115 on BrowserStack - it was added as there's an ESR version of Firefox 115, but ESR versions may be different, e.g. for some time ServiceWorker was disabled on ESR versions: https://bugzilla.mozilla.org/show_bug.cgi?id=1547023
Example test runs:
* https://github.com/mgol/jquery/actions/runs/10710118685/job/29696215652
* https://github.com/mgol/jquery/actions/runs/10710118685/job/29696215823

Tests: Run tests on both real Firefox ESRs

---

src/manipulation.js
src/manipulation/getAll.js
test/unit/manipulation.js

This pull request addresses [#5214](https://github.com/jquery/jquery/issues/5214) issue in jQuery.cleanData where certain elements were being skipped during the cleanup process. The problem occurred when an element removed itself from the DOM during its own cleanup, causing subsequent elements in the list to be missed.

Manipulation: Make jQuery.cleanData not skip elements during cleanup

---

eslint.config.js

#5542 Changed the `ecmaVersion`  for unit tests to ES5 from ES2015. Added **Promise** and **Symbol** keyword in `globals ` and given them the value `false` to   ignore them while linting tests. Polyfill added for this as well as per @mgol.

Build: Enforce ECMAScript 5 in tests via ESLint

---

CONTRIBUTING.md

When backporting #5564 to `3.x-stable` I didn't notice I had some editorial changes locally that I accidentally copied. Therefore, `main` is now not aligned with `3.x-stable`. I think these changes make sense, so I'm proposing them here to align branches instead of reversing the `3.x-stable` parts.

Docs: Align CONTRIBUTING.md with `3.x-stable`

---

src/deprecated.js
src/selector.js
test/unit/deprecated.js
test/unit/selector.js

Those APIs have formally been deprecated since `3.0.0`, but they never made its way into the deprecated module.
`jQuery.expr[ ":" ]` has been removed when Sizzle got inlined into Core in gh-4395; this change restores it.
Ref gh-5570
Ref gh-4395
PR for `3.x-stable`: #5570

Selector: Properly deprecate `jQuery.expr[ ":" ]`/`jQuery.expr.filters`

---

build/tasks/lib/compareSize.js

@mgol noticed this in https://github.com/jquery/jquery/pull/5583#issuecomment-2487006240
- The regex wasn't accounting for the added `.2` in `beta.2`.
- Incremented the version number in compareSize.js so that all existing caches automatically reset.

Build: Fix pre release matching in compare size regex

---

build/tasks/lib/compareSize.js

So far, we were mostly optimizing gzipped sizes. However, using Brotli is more and more popular as all modern browsers support it and compression is much better. It makes sense to also pay attention to these numbers.
The `comparseSize` version stays at `2` as this only introduces a new field without affecting existing ones. The only drawback is comparisons with branches that didnt have Brotli computed before will return `NaN`. This can be easily fixed locally by checking out the branch and running the build, but at least we don't lose gzipped sizes in the meantime.

Build: Report Brotli sizes in compareSize

---

src/css/finalPropName.js
test/unit/css.js

The `finalPropName` util caches properties detected to require a vendor prefix. This used to cache unprefixed properties as well, but it was reported that this logic broke accidentally during a refactor. Since fewer & fewer properties require a vendor prefix and caching a few basic checks likely has negligible perf benefits, opt to saving a few bytes and remove the cache.
Ref gh-5582
Size comparison:
```
main @d5ebb464debab6ac39fe065e93c8a7ae1de8547e
raw     gz Filename
-9     -3 dist/jquery.min.js
-9     -7 dist/jquery.slim.min.js
-9     -4 dist-module/jquery.module.min.js
-9     -7 dist-module/jquery.slim.module.min.js
```

CSS: Drop the cache in finalPropName

---

.github/workflows/browserstack.yml

iOS 18 is out. It's already available in BrowserStack.
iOS is the last browser we need to bump manually in configs. It'd be cool to eventually compute the versions there as well.
3.x version of the PR: #5554

Build: Test on iOS 18, no longer test on iOS 15

---

src/core/parseHTML.js

Using a document created via:
```js
document.implementation.createHTMLDocument( "" )
```
was needed in IE 9 which doesn't support `DOMParser#parseFromString` for `text/html`. We can switch to:
```js
( new window.DOMParser() ) .parseFromString( "", "text/html" )
```
now, saving some bytes.
Size comparison:
```
main @640d5825df5ff223560c5690f1a268681c32f9fa
raw     gz     br Filename
-42    -22     -3 dist/jquery.min.js
-42    -22    -46 dist/jquery.slim.min.js
-42    -22    -72 dist-module/jquery.module.min.js
-42    -23    -19 dist-module/jquery.slim.module.min.js
```

Core: Switch `$.parseHTML` from `document.implementation` to `DOMParser`

---

test/unit/selector.js

Sizzle & the `3.x-stable` branch have tests adding a custom attribute getter to `attrHandle` and checking if selection takes it into account. `attrHandle` was removed from the `4.x` line so the tests were not ported to the `main` branch, but the `4.x` line takes standard jQuery attribute getters into account instead and we should test for that.
Backport the `3.x-stable` selector tests for custom attribute getters, changing `jQuery.expr.attrHandle` to `jQuery.attrHooks`.

Tests: Add custom attribute getter tests to the selector module

---

.github/workflows/browserstack.yml

As of January 2025, iOS 10 is a tier 4 device on BrowserStack: https://www.browserstack.com/device-tiers
That leads to devices with this iOS version often not being available and failing our tests. Remove it from the test matrix. Also, add comments explaining the status of tests on various iOS versions, including iOS 7 that we stopped testing on a long time ago.

Build: Stop testing on iOS 10

---

src/attributes/attr.js
test/unit/attributes.js

The `hidden` attribute used to be a boolean one but it gained a new `until-found` eventually. This led us to change the way we handle boolean attributes in jQuery 4.0 in gh-5452 to avoid these issues in the future.
That said, currently from the attributes we treat as boolean only `hidden` has gained an extra value, let's support it.
Ref gh-5388
Ref gh-5452
The cost is currently quite high:
```
3.x-stable @fc874a0e125b01c2d91b4a8a06213bf1f1e5bfb6
raw     gz     br Filename
+157    +66    +58 dist/jquery.min.js
+157    +52    +36 dist/jquery.slim.min.js
```
It's possible it could be lowered if we removed the infra for adding future attributes to the list and just mentioned `hidden` & `until-found` explicitly in both the getter & setter.
Another alternative is to avoid changing the `3.x` …

Attributes: Support the `until-found` value for the `hidden` attribute

---

src/event.js

So far, a result of an event handler has been assigned to the `returnValue` of the original event by jQuery. Initially, one could pass a message the browser will then display to the user. Since that got abused a lot, every browser stopped using the provided string and they all now provide a generic message. From the browsers supported in v4, only IE 11 would still display the message.
Incidentally, IE 11 is the only browser from our supported ones which respects the value returned from a beforeunload handler attached by `addEventListener`; other browsers do so only for inline handlers, so not setting the value directly shouldn't reduce any functionality.
This looks like a good moment to stop passing the message through and just call `event.preventDefault()` without extra checks which is …

Event: Use `.preventDefault()` in beforeunload

---

src/css.js
src/css/support.js
test/unit/dimensions.js
test/unit/event.js
test/unit/support.js

Changes:
1. Fix measurements of `<col span="2">` elements in Firefox.
2. Fix measurements of all implicitly sized `<col>` elements in Safari.
3. ~~Don't try to show elements hidden via `display: none` before measuring their width or height. The styles we used to apply included `position: absolute` which could influence the styles anyway, so this was never reliable.~~ backed out
Firefox always reports computed width as if `span` was 1. In Safari, computed
width for columns is always 0. Work around both issues by using `offsetWidth`.
In IE/Edge, `<col>` computed width is `"auto"` unless `width` is set explicitly
via CSS so measurements there remain incorrect. Because of the lack of a proper
workaround, we accept this limitation.
Fixes gh-5628
Size diff:
<strike>
```
main …
```

CSS: Fix dimensions of table `<col>` elements

---

test/unit/attributes.js

The `hidden` attribute used to be a boolean one but it gained a new `until-found` eventually. This led us to change the way we handle boolean attributes in jQuery 4.0 in gh-5452 to avoid these issues in the future.
We haven't added an explicit test for the `"until-found"` value of the `hidden` attribute which triggered this decision so far, though. Backport the test from gh-5607 which landed on `3.x-stable` so that we do test it.
Ref gh-5452
Ref gh-5607
(cherry picked from commit 85290c59724db69a3967885892d4305d76de058f)

Tests: Backport the `hidden="until-found"` attr tests from 3.x-stable

---

eslint.config.js

It used to be necessary when we still had the `selector` outer IIFE, but that got simplified.

Build: ESLint: Remove the `outerIIFEBody` exception to `indent`

---

src/core.js
src/deprecated.js
test/unit/deprecated.js

Since we inlined Sizzle into jQuery, we haven't been actually using these three
methods internally. Therefore, we could add deprecation warnings in Migrate 3.x
for them with jQuery 3.7.0 or newer - both 3.7.0 & 3.7.1 pass all the tests
with them removed (while 3.6.4 does not).
Some basic tests were added as well.

Core: Formally deprecate push/sort/splice

---

test/unit/ajax.js

The original test's `text` variant just repeated the previous test with 3 parameters; the goal was to use 4 ones. This fixes it.
Ref gh-5640
Ref gh-5645

Tests: Fix tests for `jQuery.get( String, null-ish, null-ish, String )`

---

.github/workflows/node.js.yml

This is a 3.x version of gh-5682.
The `-j` switch passed to `tar` indicates the archive is compressed using the bzip2 format (`bz2` extension). That was how Firefox used to be compressed until recently, but the new ESR release now uses xz. Ubuntu `tar` doesn't auto-guess the encryption algorithm, so to support both, first try with xz and fall back to bzip2 if that fails.
Note: this will download the old Firefox ESR twice, but it will still work when the current ESR version starts to use xz with no changes to the code
Ref gh-5682

Build: Try to unpack Firefox ESR via xz, fall back to bzip2 (3.x)

---

build/tasks/minify.js
src/wrapper-esm.js
src/wrapper-factory-esm.js
src/wrapper-factory.js
src/wrapper.js

Switch https://jquery.org/license to https://jquery.com/license/, note the trailing slash. Leave the trailing slash from the minified version to save size.
3.x version: #5686

Build: Update the jQuery license link in comment headers

---

.github/workflows/browserstack.yml

JTR doesn't take into account the jump from Safari 18 to 26, so we need to specify versions explicitly. Also, while BrowserStack already added macOS Tahoe with Safari 26, it's not a stable release yet, so we need to test on Safari 17 as well.
Ref jquery/jquery-test-runner#17

Build: Test on Safari 18 & 17 instead of "latest-1"

---

test/data/testinit.js

Previously, we used example.com. However, that one is rate-limited, causing us frequent unit test failures.

Tests: Use releases.jquery.com as external host for AJAX testing

---

.github/workflows/browserstack.yml
.github/workflows/filestash.yml
.github/workflows/node.js.yml

Our setup is pretty standard, so manual configuration of `actions/cache` is an overkill. Relying on built-in `actions/node` caching will also resolve differences between caching configurations for macOS/Linux vs. Windows.
Also, switch from `npm install` to `npm ci` in CI.
Ref jquery/jquery-migrate#597
Ref gh-5702
`main` version: #5702

Build: Simplify caching in CI, use `npm ci` (3.x)
